### ISSUE TITLE
Any easy way to fix this?

### ISSUE THREAD

**Issue by UsernameNotAvailable** [afawcett/declarative-lookup-rollup-summaries#118]
I get this error when I try to deploy the child trigger:

Error:
Test_UpdateOpportunityPricingTierCtrl.testCase1 System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [CommercientSF__ExternalKey__c]: [CommercientSF__ExternalKey__c] Class.Test_UpdateOpportunityPricingTierCtrl.testCase1: line 30, column 1

Warning:
.null:Average test coverage across all Apex Classes and Triggers is 69%, at least 75% test coverage is required.

Thanks!

**Comment by afawcett** [comment]
Only by contacting the original author of the Test_UpdateOpportunityPricingTierCtrl Apex test, it seems at a guess, i'd say the CommercientSF__ExternalKey__c was added without the test being updated. Due to the way the Salesforce Metadata API works when deploying code, it cannot avoid the requirement to ensure that ALL unmanaged tests are valid.
