### ISSUE TITLE
Validation Errors

### ISSUE THREAD

**Issue by CraigWard1981** [afawcett/declarative-lookup-rollup-summaries#134]
Hi,

I've installed the latest version into sandbox and it is working fine when used to count the number of active Contacts I have associated with an Account, however when I write a Validation Rule to limit the number of Contacts (in this instance 8) I get the following error message:

Upsert failed. First exception on row 4; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id 001L0000006U4gjIAC; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Too many active contacts: [] (dlrs) Trigger.dlrs_ContactTrigger: line 7, column 1: []
Error is in expression '{!ave}' in component <apex:commandButton> in page dynamiccontact: Class.addAttendee.ave: line 28, column 1

An unexpected error has occurred. Your development organization has been notified.

Do you have any idea what this could be? If you need any further information then please let me know. 

Regards

Craig

**Comment by afawcett** [comment]
It seems your validation rule is firing 'Too many active contacts' is present in the message your getting, are you saying its firing incorrectly?

**Comment by CraigWard1981** [comment]
Hi Andrew,

Thanks for getting back to me. The validation message is correct - it's all of the other text surrounding it that I don't understand (and would like to get rid of!)

Regards

Craig

**Comment by afawcett** [comment]
I see, have had a look at the try/catch feature in Apex programming language, you can catch the exception and call the getMessage method. Or you can catch the DMLException and this class has some more specific methods on it that may give just the message text. Sadly though due the error being raised while being inside another peace of Apex code in another trigger, this tends to be the way the platform surfaces the text. The only thing if the above methods don't work, is to do a try/catch and parse the text out yourself. I'm sorry i'm not able to give more programming details on try/catch, DMLException methods etc at the moment.

**Comment by PacificScienceCenter** [comment]
Hi Andy,
Our consulting partner is receiving a similar error regarding the contact trigger as related to their custom contact rollup fields:

*First error: Update failed. First exception on row 0 with id 003o000000OvxdCAAR; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate
caused by: System.NoAccessException: Entity is not api accessible*

Our consultant requested that we adjust this trigger to run in a batch at a different interval of theirs (twice daily 12am and 11am) instead of (before delete, before insert, before update, after delete, after insert, after undelete, after update). It is their opinion that the trigger is making our roll up jobs unable to calculate. Am I able to adjust this?

Here [https://na17.salesforce.com/003o000000XnQBv?srPos=0&srKp=003](url) is an example of a contact record with a field that is failing to update correctly; the particular fields are "Last Gift Amount" and "Date of Last Gift". The fields are just calculating incorrectly at the moment, I've also attached a screenshot of where the fields are located on the layout.
![capture_dlrs_contacttrigger_error_3-18-16](https://cloud.githubusercontent.com/assets/16766848/13891065/32c8f0ce-ed0c-11e5-8731-197b3c044616.JPG)

Let me know if this can be adjusted or if this issue is a product of any custom installations by our consulting partner.

Thank you!
Devan Larson
Pacific Science Center

**Comment by afawcett** [comment]
This appears to be a different error and not associated with this original post, same child object yes, but different in other regards. It hard for me to comment as to whats causing the error without more information, can you give a screenshot of your rollup definition and the steps that result in this error.

**Comment by afawcett** [comment]
Can you also do this on a new GitHub issue please. Thank you.

**Comment by PacificScienceCenter** [comment]
will do, new issue here: [https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/319](url)

thanks
