### ISSUE TITLE
System.DmlException: Update failed

### ISSUE THREAD

**Issue by Inbarajd** [afawcett/declarative-lookup-rollup-summaries#163]
Hi, 
I have a custom object called Countries which is lookup relationship to Case object. My condition is a case record should have a country value when case is closed. I have a validation rule which will check for the condition at the time of case closed. Which is working fine by using the DLRS. My issues is when there is only one country and user try to delete the country when case is closed. I am getting the error

Sandbox

Apex script unhandled trigger exception by user/organization: 005r0000000Hsdx/00Dr00000000OWK Source organization: 00Dt0000000Gydl (null)
dlrs_RelatedCountriesTrigger: execution of AfterInsert

caused by: System.DmlException: Update failed. First exception on row 0 with id 500r0000000nmcyAAA; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, To create a case, you must specify the related organization or a contact related to that organization.: [AccountId]

(dlrs)

Trigger.dlrs_RelatedCountriesTrigger: line 7, column 1

Validation Rule:
AND( CASE( Status , "Successfully Closed", 1, "Administratively Closed", 1,"Unable to Resolve",1,0)=1,Country_in_Case_Rollup__c = 0)

Country_in_Case_Rollup__c is the field in Case object which has the number of country values.

I am not able to find what is wrong. Can you please help me in fixing this issue.

Thanks,
Inbaraj

**Comment by afawcett** [comment]
I'll try to reproduce this for you.

Can you include a screenshot of your rollup please.

Also the validation rule needs to be added to the Case object, yes?

**Comment by Inbarajd** [comment]
Thanks for the reply. Yes I have the validation rule in Case object. Here is the screen shot.

![image](https://cloud.githubusercontent.com/assets/8289753/7442864/5d9686e4-f0f1-11e4-843d-fc391dac3a43.png)

The Validation rule is.

![image](https://cloud.githubusercontent.com/assets/8289753/7442874/c655ef30-f0f1-11e4-8821-2341fce066d3.png)

**Comment by afawcett** [comment]
What does your RelatedCountries__c object look like under Setup?

**Comment by Inbarajd** [comment]
![image](https://cloud.githubusercontent.com/assets/8289753/7445285/523a399c-f17a-11e4-97f6-f749f8069672.png)


And the field which i am using to calculate. ie Count

![image](https://cloud.githubusercontent.com/assets/8289753/7445292/996fc6ce-f17a-11e4-822b-a73c2d1a22c8.png)

**Comment by afawcett** [comment]
The image for the formula seems to be corrupt, i cannot make out the actual formula?

**Comment by aheber** [comment]
If I had to guess I think the formula looks like a "Power of One" formula
field so it is a formula that always returns 1.

**Comment by Inbarajd** [comment]
Hi Andy,
The validation rules is:
AND( CASE( Status , "Successfully Closed", 1, "Administratively Closed", 1,"Unable to Resolve",1,0)=1 ,Industry_Rollup_Sum__c = 0)

**Comment by afawcett** [comment]
Sorry for the delay in getting round to this, i've been on holiday.

I've reproduced the setup for what i think you have above.

However I cannot reproduce the error message.

When i have a case with status Successfully Closed and at least one Country related.

When i attempt to delete the Country i get the following error message...

There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger dlrs_RelatedCountriesTrigger caused an unexpected exception, contact your administrator: dlrs_RelatedCountriesTrigger: execution of AfterDelete caused by: System.DmlException: Update failed. First exception on row 0 with id 500b0000001hm1bAAA; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Case cannot be closed without country: []: (dlrs)". 

Which in my view is expected, yes?

Looking at your original error however...

To create a case, you must specify the related organization or a contact related to that organization.: [AccountId]

This makes me wonder if there is another Validation Rule on the Case that is causing this problem, can you check?

**Comment by Inbarajd** [comment]
Hi Andy,

Thanks for your reply. The error is correct, but we want to show user-friendly error message to the user and we do not want users to receive the Apex generated error email message for exceptions. How can we achieve that ?

Thanks,
Inbaraj.

**Comment by afawcett** [comment]
Ah I see. I'm sorry this is due to the error being caught indirectly by another peace of code. I share your desire to make it more user-friendly i've had the same thing with other things like this on the platform. If its a Visualforce page and controller you could perhaps catch the exception and parse the string to remove the bits you don't want. But if its a native UI page, your a bit stuck with how Salesforce surfaces this sorry.
