### ISSUE TITLE
Error on trigger activation in production

### ISSUE THREAD

**Issue by karmenta** [afawcett/declarative-lookup-rollup-summaries#166]
Hello,

I'm running into an error when I activate the trigger in two different rollups. The first, rolling up a field from opportunities to a campaign and second, rolling up opportunities (donations) to a household. 

In sandbox, they work fine. In production I receive the following error. We are also in the process of implementing Financial Force Accounting, and it seems like that may have something to do with it? Any thoughts on how I might get these to work is much appreciated.

![screen shot 2015-05-07 at 8 47 02 pm](https://cloud.githubusercontent.com/assets/12348529/7540812/168756d2-f576-11e4-8aa3-3e1122785250.png)

Thanks,

Kelly

**Comment by afawcett** [comment]
The tool requires (because the platform does) that ALL unmanaged (those not contained in installed AppExchange packages) Apex tests complete successfully to deploy its own trigger Apex code. This is an underlying requirement of the platform. Thus if you had to deploy any new code to this production org (via ChangeSet's for example), you would see the same errors. My suggestion is to reproduce the test failures via the Setup > Apex Test Execution page and submit a support case to FinancialForce.com who do appear to be the author of majority of the failures. Perhaps with the exception of MyProfilePageControllerTest class?

**Comment by afawcett** [comment]
You may also want to ask when raising the case if some of this unmanaged connector code has been moved to managed packages, which would isolate them from unmanaged deployments in the future.

**Comment by karmenta** [comment]
Thank you! I'll give that a try.
