### ISSUE TITLE
Deploying Trigger issue

### ISSUE THREAD

**Issue by girlyITgeek** [afawcett/declarative-lookup-rollup-summaries#205]
I have been having trouble deploying a trigger. I have upgraded to 1.22 so I was hopeful it might be fixed. Note: I tried deploying last week after installing 1.20 and I only received the top error. When trying today after installing 1.22 I received the code coverage issue also.

Any help on the below error would be greatly appreciated! Thanks. 

Error:
dlrs_AVTRRT_PlacementTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, AVTRRT.Trigger_Placement: execution of BeforeInsert caused by: System.QueryException: List has no rows for assignment to SObject (AVTRRT) : [] (dlrs) Class.dlrs_AVTRRT_PlacementTest.testTrigger: line 11, column 1

Warning:
dlrs_AVTRRT_PlacementTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

**Comment by afawcett** [comment]
There is an issue in the AVTRRT.Trigger_Placement Apex Trigger, which looks like its from another managed package. Which i suspect is due to the code in that trigger not properly tolerating inserting a record without any field values being set. Take a look at this [wiki page](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) as way to use the new features in v1.22 to customise the Test code to make it work for this object. 

    BeforeInsert caused by: System.QueryException: List has no rows for assignment to SObject (AVTRRT)

**Comment by girlyITgeek** [comment]
Thank you
