### ISSUE TITLE
Add developer API to mirror triggerHandler behavior

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#236]
Add developer API to mirror triggerHandler behavior

**Comment by afawcett** [comment]
Fixed in v1.23

**Comment by afawcett** [comment]
See [API doc here](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupService.cls#L165)

**Comment by wes1278** [comment]
@afawcett I've tried to get this developer API to work and I just can't seem to get it to work.

I have a custom object "Order_Item__c" that should roll up sum of all costs to an "Order__c" object. So, I have a pre-existing trigger on order item. should I just be able to write one line of code "dlrs.RollupService.rollup(trigger.oldMap,trigger.newMap,Order_Item__c.SObjectType);"

Is that correct? I feel like I tried that and I didn't see it work. Perhaps I just need to pay better attention. But, can you confirm I'm doing what should be possible?

Thanks!

**Comment by gokubi** [comment]
Please remove sandersen@grameenfoundation.org from this list serv  Thanks







*From:* Wes Weingartner [mailto:notifications@github.com]
*Sent:* Wednesday, April 06, 2016 11:46 AM
*To:* afawcett/declarative-lookup-rollup-summaries
*Subject:* Re: [afawcett/declarative-lookup-rollup-summaries] Add developer
API to mirror triggerHandler behavior (#236)



@afawcett <https://github.com/afawcett> I've tried to get this developer
API to work and I just can't seem to get it to work.

I have a custom object "Order_Item__c" that should roll up sum of all costs
to an "Order__c" object. So, I have a pre-existing trigger on order item.
should I just be able to write one line of code
"dlrs.RollupService.rollup(trigger.oldMap,trigger.newMap,Order_Item__c.SObjectType);"

Is that correct? I feel like I tried that and I didn't see it work. Perhaps
I just need to pay better attention. But, can you confirm I'm doing what
should be possible?

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/236#issuecomment-206436487>

**Comment by afawcett** [comment]
Yes this should [be the one](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupService.cls#L210), have you set your rollups to type Developer?
