### ISSUE TITLE
Possible to schedule a full recalculation

### ISSUE THREAD

**Issue by SecretSighter** [afawcett/declarative-lookup-rollup-summaries#263]
We have some rollups in our organization that we would like to recalculate on a weekly or monthly basis, and if no child records have been created/updated/touched then the parent record should get a 0. Is this possible?

**Comment by afawcett** [comment]
This is not currently possible no, the schedule mode is purely picking up queued / logged changes to child records for later processing. This issue is similar to the existing enhancement [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/142) and [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/146). Take a look at these and/or add commetns as required. If you think neither reflect your needs we can re-open this one for sure. :+1:
