### ISSUE TITLE
apex.bytecodeinterpreter.InterpreterRuntimeException: Unable to load class: dlrs/SObjectDomain

### ISSUE THREAD

**Issue by jsullivanlive** [afawcett/declarative-lookup-rollup-summaries#290]
I get the following error using the managed package install of DLRS and started getting an internal server error when editing my DLSR settings records.  I don't get the managed package emails so I can't tell what is causing it.  If you tell me what the error was, I can help make a fix in the package with a pull request.  Here's what salesforce support said about the internal server error:

(Case # 13040266)

> I received an update from Tier 3 Support regarding your concern.
>
> Subject of the error is the following:
> apex.bytecodeinterpreter.InterpreterRuntimeException: Unable to load class: dlrs/SObjectDomain
>
> This Object is part of a managed package as is the Apex Class involved:
>
> Apex Class
> RollupSummaries
> https://cloudanswers.my.salesforce.com/01pa00000018OKX
> 
> As advised by Tier 3 Support, please contact the Developer of the app "Declarative Lookup Rollup Summaries Tool" which is listed as "andyinthecloud.com" for further assistance as Salesforce does not have visibility into the code since this is a third-party package.
> 
> I will now proceed to close our case with your consent.  If you feel that you need any additional help, remember that you may open a case through the customer portal.
> 
> Sincerely,

**Comment by afawcett** [comment]
This is very much an internal Salesforce error, not one in the Apex code of the tool. What it looks like is some problem loading the internal byte-code of the Apex class, again, this is internally how our Apex code is compiled within the platform. I can only suggest workarounds or ways to clean up what i think is corruption in the orgs Apex cache (something SF really need to address, tier 3 are really just giving you generic response here without treating it as a platform issue). Try going to Apex Classes and hitting Compile All link see what happens then. Code that is packaged, has to compile or the upload will fail, since your installing a managed package this has to be a platform issue. Hope this helps!

**Comment by jsullivanlive** [comment]
Support won't relinquish the issue information to me, so I can't help track down the issue.  I asked that they put it in this github issue but they said they would only communicate it to you.  If you're willing to put it here, I'm really happy to open a PR with a fix.

**Comment by afawcett** [comment]
They have contacted me and asked ...

"Our Tier 3 Support is requesting for you to log a case with us so that further troubleshooting can be done directly between you and them. I hope that we can get this taken care of for our customer."

Which i've now done, case number 13139350. Based on the above i'm now sure what assistance they want from me, i assume they will tell me in due course.... I suggest in the meantime you let them know i've raised case 13139350 and hopefully this will keep things moving... :+1:

**Comment by jsullivanlive** [comment]
Salesforce support said your case, number 13139350, is closed because it's a duplicate case and we "should put it on the idea exchange"   :rage1:

**Comment by afawcett** [comment]
Hmmm ok thanks for the update, i was notified or asked about the closure of my case. I'll see if i can get an explanation from my end for us here.

**Comment by afawcett** [comment]
Sounds like we have this sorted now. For the record it seems like it was a platform bug of some kind, Salesforce opened the trigger code in dev console i think and just hit save, this seemed to sort it.

**Comment by jsullivanlive** [comment]
@afawcett thanks a ton, and sorry you had to endure the support process and all that emailing.

If anyone is reaching this page by searching for internal server error and managed package, make sure to execute an apex code recompile:

https://help.salesforce.com/apex/HTViewHelpDoc/HTViewHelpDoc?id=code_manage_packages.htm&language=en_US

> Click Compile all classes to compile all the Apex classes in your organization. If you have classes that are installed from a managed package and that have test methods or are test classes, you must compile these classes first before you can view them and run their test methods from the Apex Test Execution page. Managed package classes can be compiled only through the Compile all classes link because they cannot be saved. Otherwise, saving Apex classes that aren't from a managed package causes them to be recompiled. This link compiles all the Apex classes in your organization, whether or not they are from a managed package.

**Comment by afawcett** [comment]
No worries, happy it got sorted for you in the end! :+1:
