### ISSUE TITLE
DLRS Doesn't see PricebookEntry.Product2 in getDescribe of OpportunityLineItem

### ISSUE THREAD

**Issue by deckblad** [afawcett/declarative-lookup-rollup-summaries#294]
I'm trying to build a query that will filter on OpportunityLineItem.PricebookEntry.Product2.Foo__c.  I'm trying to build a query like: 
"select count(id) from OpportunityLineItem where PricebookEntry.Product2.Foo__c = true"
...That would then roll up to Opportunity.
I've verified that the SOQL does indeed work. But, something's blocking it in you validation. Or, I don't know what I'm doing. Could you please provide your insight?

Here's a screenshot.
![dlrserror](https://cloud.githubusercontent.com/assets/4379218/12757572/36d63096-c99e-11e5-9579-310cde0a8d3a.png)

Thank you.

**Comment by afawcett** [comment]
Yes sorry this is not supported as your hoping. It might be a valid query, but currently DLRS only monitors immediate fields on the child object, it does this to only calculate the rollup when needed, as a performance optimisation. 

So while you could probably bubble the value of Foo_c back up the relationships via a Formula field, due to the way Formula fields work DLRS would not notice the change on the underlying field on Product. The only way to get the Formula field workaround to work, is to use the Calculate Schedule button to schedule a full recalculate of the parent record rollups at 2am in the morning. 

Your not the first person recently to want this, so i'm going to formulate an enhancement to see if the tool can support this. It would likely require deployment of another trigger or workflow rule on related records to the child object to monitor for field changes and trigger a rollup recalc though.
