### ISSUE TITLE
Test Code Field - New UI- Commented out? 

### ISSUE THREAD

**Issue by wkoscielny** [afawcett/declarative-lookup-rollup-summaries#307]
I ran into an issue when testing this out with my organization and using the new UI that allows for Custom Metadata.  The Test Code field is not available when viewing.  I took a glance at the visual force page associated with this and noticed the following. Looks like it was commented out? It works when I use the normal custom object UI without issue.  Any reason it was commented out?
```
<apex:pageBlockSection title="Advanced" columns="1">
					<!--
					<apex:pageBlockSectionItem helpText="{!$ObjectType.LookupRollupSummary2__mdt.fields.TestCodeDocument__c.inlineHelpText}">
						<apex:outputLabel value="{!$ObjectType.LookupRollupSummary2__mdt.fields.TestCodeDocument__c.Label}"/>
						<apex:inputText size="32" value="{!LookupRollupSummary.TestCodeDocument__c}"/>
					</apex:pageBlockSectionItem>
					-->
					<apex:pageBlockSectionItem helpText="{!$ObjectType.dlrs__LookupRollupSummary2__mdt.fields.dlrs__TestCodeSeeAllData__c.inlineHelpText}">
						<apex:outputLabel value="{!$ObjectType.dlrs__LookupRollupSummary2__mdt.fields.dlrs__TestCodeSeeAllData__c.Label}"/>
						<apex:inputCheckbox value="{!LookupRollupSummary.dlrs__TestCodeSeeAllData__c}"/>
```

**Comment by afawcett** [comment]
It's due to the fact that Custom Metadata doesn't support Large Text Area field types currently. I've called it out as a restriction of the current pilot functionality. Other users have managed to find the 255 limited version of this field via editing the custom metadata record via the Custom Metadata page under Setup, though obviously this only currently works if your snippet of test code is under 255 characters. I've raised an enhancement request to sort this restriction out via some kind of workaround to the platform limitation above.  https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/304
