### ISSUE TITLE
Installation Error - Remote Site Setting

### ISSUE THREAD

**Issue by Thainternut** [afawcett/declarative-lookup-rollup-summaries#321]
I just installed DLRS in my Sandbox and am getting errors with creating the Remote Site Setting. I saw similar issues (#102 and #110), but still no resolution. I had to create the Remote Site Setting manually because the button would not work and am now receiving the error message:

Unable to connect to the Salesforce Metadata API.
Web service callout failed: WebService returned a SOAP Fault: INSUFFICIENT_ACCESS: Insufficient access; cannot execute Metadata operation with PAC enabled session id faultcode=sf:INSUFFICIENT_ACCESS faultactor=

Thanks in advance for your help.

**Comment by afawcett** [comment]
There is some discussion on this here, https://github.com/financialforcedev/apex-mdapi/issues/6. Can you also go to the Installed Packages page and click the package then check the API Access field?

**Comment by afawcett** [comment]
Let me know if your still having this and we can re-open. 👍

**Comment by kopperwoman** [comment]
Hi Andrew,

I see you closed this discussion and linked to financialforcedev/apex-mdapi#6 instead. I read through that and I'm not sure I see an answer to this issue. 

I have DLRS 2.9 installed and working in my production environment. We've been using it since version 1.1 in mid-2014. 


A couple of months ago created a Partial Copy sandbox. When I did, I had to add a Remote Site Setting in the sandbox to allow access to the Salesforce Metadata API for my organization. I believe I used the "Create Remote Site Setting" button on the DLRS setup screen, and that it worked, but I can't remember for sure now because it was a while ago. I got it working properly in my Partial copy sandbox and I was happy!

Recently I refreshed the data in my Partial copy and now I'm getting the same message--that I need to add a remote site setting to allow access to my organization's Salesforce Metadata API. This time when I tried the button in the DLRS screen it didn't work. 

Can you please let me know what I need to do to set this up by hand? I'm happy to provide more details/screenshots if they would be helpful. Thanks.

**Comment by aheber** [comment]
@kopperwoman if you navigate to Remote Site Settings in setup, you'll find a site setting named "dlrs_mdapi." I would just delete that and then use the Create Remote Site Setting button in DLRS again. Should work, let us know.

**Comment by kopperwoman** [comment]
Hi Anthony @aheber (sorry, tag didn't work for some reason) that did the trick! I deleted dlrs_mdapi from the remote site settings list and used the button to create a new one, no problems at all. Thanks for your quick response.

**Comment by btbaker1** [comment]
I'm having the same issue.  However, I had set up a remote site and it worked fine.  Now all of a sudden it does not work anymore.  I tried deleting it and adding a new one with the site they provide, but I'm still getting a error message.
![screen shot 2019-01-08 at 5 48 14 pm](https://user-images.githubusercontent.com/46506551/50866169-7f06e780-136e-11e9-83fb-0c6b8ad388ea.png)
