### ISSUE TITLE
An Apex error occurred: System.LimitException: Apex CPU time limit exceeded 

### ISSUE THREAD

**Issue by tamilust** [afawcett/declarative-lookup-rollup-summaries#338]
I am using a DLRS job in a Process Builder. As of late I have been getting a lot of flow application error reports. These flows are scheduled to run 1 minute after the creation date. I am using a formula field for the scheduled field. Do you know why I would be getting a time limit exceeded error?

Thanks,

Tami

**Comment by afawcett** [comment]
This is a really general error and hard to pin point due it being consumed by all code in the request not just packaged code (like the SOQL governor for example). Furthermore its non-deterministic, meaning sometimes it works, sometimes not, depends typically on the load on the service sometimes. If your getting more often than not, i'd say your closer to the tolerance used, which can be +10-15 seconds (in my experience) over the 10 seconds (interactive) or 60 second (in background) limit. 

This is what the [docs](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_gov_limits.htm) say about this...

_"CPU time is calculated for all executions on the Salesforce application servers occurring in one Apex transaction. CPU time is calculated for the executing Apex code, and for any processes that are called from this code, such as package code and workflows. CPU time is private for a transaction and is isolated from other transactions. Operations that don’t consume application server CPU time aren’t counted toward CPU time. For example, the portion of execution time spent in the database for DML, SOQL, and SOSL isn’t counted, nor is waiting time for Apex callouts."_

If you can capture a debug log (while Dev Console is open), then try to use the [Developer Console Profiler](https://developer.salesforce.com/blogs/engineering/2013/05/force-com-performance-profiling-using-the-developer-console.html) to discover where the most time is being spent. Otherwise you can try to review the raw text of the debug logs and see where large jumps in the time index in the log are made.

Hope this helps!

**Comment by afawcett** [comment]
@tamilust Please let me know if you want to continue to discuss, meanwhile i'll close this issue out. You can still add comments to it and i will still see them. Thanks.
