### ISSUE TITLE
Install failed 2.4 update - New dependency on LookupChild's Sharing mode in Apex Unit Test

### ISSUE THREAD

**Issue by sbaird80** [afawcett/declarative-lookup-rollup-summaries#344]
Getting an install failure when trying to upgrade from 2.3 to 2.4

1. Custom Object Records Missing Organization Feature: dlrs__LookupChild__c.Sharing null

**Comment by jongpie** [comment]
I'm getting this too when upgrading from 2.2 to 2.4

**Comment by afawcett** [comment]
Thanks both. This is the first time i've used the Salesforce Release Patch feature hence the ".1" in the "2.4.1" release version. I'm wondering if something is different in this process. Starting to investigate....

**Comment by afawcett** [comment]
We have been discussing this in the Chatter gorup, this is the workaround...

"Can you go into Sharing Settings under the Setup menu and check if 'Lookup Child' has Private sharing set for it. Note that this object is used only to support the Apex tests in the package and does not contain any data."

I'm raising this as a bug now, as i've seen what caused this, ironically an Apex test i wrote brought in an a dependency on one of the test objects that get included in the package as requiring a private sharing model. Which for new installs is the case, but if your one of those that's been tracking the tool from the start, its not always been the case that this test object was set to private sharing and since this doesn't upgrade was never changed following upgrades. Which prior to this dependency was never really any issue... Phew that hurt my head a bit... Sorry folks.

**Comment by jongpie** [comment]
Ok, so I updated the sharing settings for the Lookup Child object - it was previously public read/write and I changed it to private. After the sharing settings were recalculated, I was able to update to 2.4.1!

**Comment by afawcett** [comment]
Excellent!

**Comment by afawcett** [comment]
Fixed in v2.4.2.
