### ISSUE TITLE
Help Text for Calculation Mode needs updating

### ISSUE THREAD

**Issue by afawcett** [afawcett/declarative-lookup-rollup-summaries#350]
From Chatter 
![dlrs2](https://cloud.githubusercontent.com/assets/1167760/16540566/3042a23e-4061-11e6-9070-a358c04e6b51.png)

"Seems the default help text for Calculation Mode need to update to include Scheduled, as it also need to deploy child trigger, but correct me if I am wrong"

**Comment by JimBTek** [comment]
I think it is correct because if it is Scheduled Mode you do not need to set it as Active.   I have Scheduled rollups that run on a schedule without the triggers and without being marked as active.

**Comment by zak456** [comment]
Could someone verify whether JimBTek is correct? I very much want to have scheduled rollups without needing the child trigger. But I can't see how the scheduled rollup would be able to only re-calculate the children that have changed if there's no child trigger to keep track of that. Or am I missing something?

**Comment by KevStarSF** [comment]
I have had the same performance as JimBTek, Scheduled Rollups will run even if the Rollup is de-activated.  I believe the Active checkbox only applies to Realtime mode.

**Comment by zak456** [comment]
Perhaps we are not talking about the same thing. I am not using "Schedule Calculate". That does a complete recalculation of every record for the rollup. I am using the scheduled Apex job "rollupjob", which will only recalculate rollups for the records that have been added/deleted/updated since the last run. That is needed because we have too many records and would take too long to do a calculation every night. I have tried doing this without deploying the child trigger, and without making the rollup active. It seems to be that both are needed. But if I am missing something, I would definitely want to hear because I would love to remove the child trigger as it sometimes causes conflicts.

**Comment by afawcett** [comment]
"But I can't see how the scheduled rollup would be able to only re-calculate the children that have changed if there's no child trigger to keep track of that. Or am I missing something?" No your not, i plan on updating the tool to make the two schedule modes more clear. But you have got it in the meantime, Schedule Calculate does not require a trigger and does full recalc on the schedule each time (set the Calculation Mode to something like Process Builder). For Calculation Mode = Scheduled, you need the trigger to log what parent records need updating and thus make the RollupJob you schedule via Apex Classes more efficient. True you can schedule this without any rollups defined for Scheduled mode, but it would not do anything then.

**Comment by afawcett** [comment]
Fixed v2.8.

**Comment by camisotro** [comment]
Just a comment - how about changing the name of the "Scheduled" calculation mode to "Deferred"? Cause the onus is on the admin to schedule the calculation, whereas "Scheduled" makes it sound like DLRS will do it for you.
