### ISSUE TITLE
1\nClass.dlrs.RollupService.UpdateWithoutSharing.updateRecords

### ISSUE THREAD

**Issue by sarahDTMCSF** [afawcett/declarative-lookup-rollup-summaries#358]
Hi,

First of all, I love this tool!  However, for the first time I am getting the following errors and it seems like the entity deleted error is not being removed from the cache, if that makes sense.  Shouldn't the DLRS try to re-run?  For the sharing error, I have no clue here.  Any insight is great!!  Thank you!

CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_Zuora_PaymentTrigger: execution of AfterInsert\n\ncaused by: System.DmlException: Update failed. First exception on row 0 with id a18d0000004bbPvAAI; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_Zuora_CustomerAccountTrigger: execution of AfterUpdate\n\ncaused by: System.DmlException: Update failed. First exception on row 28 with id 001d000001tAstoAAC; first error: ENTITY_IS_DELETED, entity is deleted: 

1\nTrigger.dlrs_Zuora_CustomerAccountTrigger: line 7, column 1: []\n\nClass.dlrs.RollupService.Updater.updateRecords: line 1159, column 1\nClass.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1178, column 1\nClass.dlrs.RollupService.updateRecords: line 1131, column 

Thanks!

**Comment by afawcett** [comment]
Thanks for the feedback! 👍 While i'm not sure what you mean by the cache comment. Typically this is due to some other logic associated with the child record being updated, resulting in the parent record being deleted. Is this possible? Also check your on the latest version, there was an older issue that didn't spot deleted parent records.

I think also its safe to ignore the sharing references here, this is just due to your rolling going through the sharing code path, based on how set the Sharing mode, you can try it in System mode by selecting that on the rollup definition. But i don't think its relevant tbh. Hope this helps.

**Comment by afawcett** [comment]
I'll close this issue out for now, however you can still add comments and if needed we can re-open. Thanks. 👍
