### ISSUE TITLE
Null pointer exception when updating child objectin Class.dlrs.RollupService.updateMasterRollupsTrigger

### ISSUE THREAD

**Issue by woutersmet** [afawcett/declarative-lookup-rollup-summaries#399]
I have a custom invoice__c object in our org, which points to an opportunity (relabeld to Project in our org). I have a couple of rollup summaries related to this, but lately when I try to fill the lookup field on an Invoice object, it gives me the following error:

Error:Apex trigger dlrs_InvoiceTrigger caused an unexpected exception, contact your administrator: dlrs_InvoiceTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object: Class.dlrs.RollupService.updateMasterRollupsTrigger: line 938, column 1

I have removed all scheduled jobs related to invoice/opportunity lookups as the code seems to have something to do with that, but no luck :( 

Deactivating the triggers doesn't work, but removing the child trigger on the invoice does.

**Comment by woutersmet** [comment]
Here is the full error email + subject, some more stack trace info in there that is useful maybe:

Apex script unhandled trigger exception by user/organization: 00524000000EaX8/00D24000000IKvL

dlrs_InvoiceTrigger: execution of AfterUpdate

caused by: System.NullPointerException: Attempt to de-reference a null object

Class.dlrs.RollupService.updateMasterRollupsTrigger: line 938, column 1
Class.dlrs.RollupService.handleRollups: line 815, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_InvoiceTrigger: line 7, column 1

**Comment by woutersmet** [comment]
Even more sure it has something to do with scheduled rollups now, as I can reproduce it by switching one specific rollup to 'scheduled' and 'realtime' does not cause it

**Comment by afawcett** [comment]
Can you try this again on the latest release, i think this has already been fixed. Let me know if not. 👍

**Comment by Shivanidesai** [comment]
Hi!
I am getting this error too he flow tried to update these records: null. This error occurred: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_ProductTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.dlrs.RollupService.updateMasterRollupsTrigger: line 894, column 1 Class.dlrs.RollupService.handleRollups: line 777, column 1 Class.dlrs.RollupService.triggerHandler: line 307, column 1 Trigger.dlrs_ProductTrigger: line 7, column 1. For details, see API Exceptions.

Can you please help to fix it?

Thank You,
Shivani

**Comment by afawcett** [comment]
This does not appear to be a line of code in the current build. What version are you running? Can you update to the latest?

**Comment by Shivanidesai** [comment]
Thanks for responding Andrew! Will it hamper the existing functionality if I update the current version?
