### ISSUE TITLE
Error deploying Child Trigger on NPSP object npe03_Recurring_Donation

### ISSUE THREAD

**Issue by RWAPS** [afawcett/declarative-lookup-rollup-summaries#490]
Hello everyone, I've upgraded to V2.8 of DLRS in my sandbox, and some Roll up summaries work fine (using the new flavour with custom metadata, via the "Manage Lookup Rollup Summaries" tab) while others, where the child object is "npe03__Recurring_Donation__c" from the Salesforce Foundation NPSP, fail to deploy.
I get 2 errors, any idea?

Error:
dlrs_npe03_Recurring_DonationTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You must select an Organization or Contact: [] Class.dlrs.RollupService.testHandler: line 272, column 1 Class.dlrs_npe03_Recurring_DonationTest.testTrigger: line 11, column 1

Warning:
dlrs_npe03_Recurring_DonationTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

My understanding from reading other issues here is that I can solve #2 by adding a custom test class (but where?), and #1 seems to be a recurring issue in relation to DLRS with NPSP (issue #197). Any updates on DLRS with NPSP? Thanks so much!
![image](https://cloud.githubusercontent.com/assets/4457855/25069475/eb8f1c4a-2281-11e7-9088-6b71a4913837.png)

**Comment by afawcett** [comment]
Yes you need to provide some custom test code in the Test Code field, i am not an expert in NPSP, hopefully someone in the Chatter group has the test code fragment you need. Meanwhile this is the background to both your errors https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

**Comment by benchastain** [comment]
@RWAPS Did you ever manage to solve your test code issue?

I just wrote test code for a trigger that rolls up recurring donations to the contact record and if you're trying to do something similar then I'd imagine my test code will work for you.

I believe I received the same error as you did in my first go round--it's because there's a validation rule on the Recurring Donation object to assign either a contact or an organization. You can do that in your test code like this (my test code also needed the custom field 'Inactive_Recurring_Gift__c' to be false):

```
Contact con = new Contact(Lastname = 'Test');
insert con;

SavePoint sp = Database.setSavepoint();
dlrs.RollupService.testHandler(new npe03__Recurring_Donation__c(npe03__Contact__c = con.id, Inactive_Recurring_Gift__c = FALSE));
Database.rollback(sp);
```

**Comment by RWAPS** [comment]
Hi @benchastain, thanks, yes I did manage to solve this. Thanks for the additional information.

**Comment by afawcett** [comment]
Thanks for sharing @benchastain, i dont have NPSP experience so depend on this kind of contribution from the community to help others. Thank you! 👍

**Comment by BHFoundation** [comment]
I could use some assistance on this same item except I am trying to roll up the GAU Allocations to the Opportunity record.   We are recording the GAU Allocations on through a lookup on the opportunity and upon save this creates the  Allocation records.  But I need to verify the allocation totals equal the opportunity total.  Any assistance would be greatly appreciated.

**Comment by BHFoundation** [comment]
Sorry here is the error I am receiving ......

![image](https://user-images.githubusercontent.com/31489994/29894438-e0bc0ab0-8d9a-11e7-87e4-d132ae9bf024.png)

**Comment by alexandr-yul** [comment]
@benchastain I wasn't able to use your code directly (it gave an error) but the following worked

`        Contact con = new Contact(Lastname = 'Test');
        insert con;

        npe03__Recurring_Donation__c recur = new npe03__Recurring_Donation__c();
        recur.npe03__Installment_Period__c = 'Monthly';
        recur.npe03__Open_Ended_Status__c = 'Open';
        recur.npe03__Schedule_Type__c = 'Multiply By';
        recur.npe03__Amount__c = 50;
        recur.npe03__Date_Established__c = System.Today();
        recur.npe03__Next_Payment_Date__c = System.Today();
        recur.npe03__Contact__c = con.Id;
        
        SavePoint sp = Database.setSavepoint();
        dlrs.RollupService.testHandler(recur);
        Database.rollback(sp);`

**Comment by benchastain** [comment]
I believe I originally wrote that code over a year ago and was written with some specific parameters for custom fields. If there have been updates to the NPSP or you have additional custom logic in your instance it would make sense that my code was not just a simple copy/paste.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Alex <notifications@github.com> Date: 2/15/18  9:43 PM  (GMT-05:00) To: afawcett/declarative-lookup-rollup-summaries <declarative-lookup-rollup-summaries@noreply.github.com> Cc: benchastain <benjamindchastain@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [afawcett/declarative-lookup-rollup-summaries] Error deploying Child Trigger on NPSP object npe03_Recurring_Donation (#490) 
@benchastain I wasn't able to use your code directly (it gave an error) but the following worked
`        Contact con = new Contact(Lastname = 'Test');

insert con;
    npe03__Recurring_Donation__c recur = new npe03__Recurring_Donation__c();
    recur.npe03__Installment_Period__c = 'Monthly';
    recur.npe03__Open_Ended_Status__c = 'Open';
    recur.npe03__Schedule_Type__c = 'Multiply By';
    recur.npe03__Amount__c = 50;
    recur.npe03__Date_Established__c = System.Today();
    recur.npe03__Next_Payment_Date__c = System.Today();
    recur.npe03__Contact__c = con.Id;
    
    SavePoint sp = Database.setSavepoint();
    dlrs.RollupService.testHandler(recur);
    Database.rollback(sp);`


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/afawcett/declarative-lookup-rollup-summaries","title":"afawcett/declarative-lookup-rollup-summaries","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/afawcett/declarative-lookup-rollup-summaries"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexandr-yul in #490: @benchastain I wasn't able to use your code directly (it gave an error) but the following worked\r\n\r\n`        Contact con = new Contact(Lastname = 'Test');\r\n        insert con;\r\n\r\n        npe03__Recurring_Donation__c recur = new npe03__Recurring_Donation__c();\r\n        recur.npe03__Installment_Period__c = 'Monthly';\r\n        recur.npe03__Open_Ended_Status__c = 'Open';\r\n        recur.npe03__Schedule_Type__c = 'Multiply By';\r\n        recur.npe03__Amount__c = 50;\r\n        recur.npe03__Date_Established__c = System.Today();\r\n        recur.npe03__Next_Payment_Date__c = System.Today();\r\n        recur.npe03__Contact__c = con.Id;\r\n        \r\n        SavePoint sp = Database.setSavepoint();\r\n        dlrs.RollupService.testHandler(recur);\r\n        Database.rollback(sp);`"}],"action":{"name":"View Issue","url":"https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/490#issuecomment-366129932"}}}

**Comment by afawcett** [comment]
Reminder to include this when delivering this idea, https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/613.

**Comment by afawcett** [comment]
I will close this out for now. We can keep chatting though and re-open the case if needed. Thanks! 😄

**Comment by aronmule** [comment]
Hi, I am getting this issue but I am not clear how to resolve based on above comments.  I am not a developer and asked ChatGPT for assistance and it generated an Apex Class based on above comments.  I can save it but deployment still does not work.  Any assistance would be appreciated.  Aron

**Comment by aheber** [comment]
@aronmule, I would recommend you start by searching the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) for DLRS. If you're unable to find an answer in existing questions please create a new question and our wonderful community will show up to help find an answer.
