### ISSUE TITLE
Modify All Data required?  Metadata API connection failure error

### ISSUE THREAD

**Issue by Bard09** [afawcett/declarative-lookup-rollup-summaries#520]
I'm unable to access the /apex/managelookuprollupsummaries page with one of our custom profiles and specifically with this profile I am getting an error: "Salesforce Metadata API connection failure, click the link below to configure."  (nothing follows it-- no text or links or anything)

DLRS does work for other profiles, though.  We have the Remote Site Setting set up correctly, no IP-level restrictions are set up, and my profile does have API access enabled.  All users have access to the /apex/managelookuprollupsummaries Visualforce Page security.

One thought for the profile I'm using: we have a requirement to not allow IT any permissions to modify data, thus the "Modify All Data" permission is unchecked and most objects are blocked for CRUD.  Are any data-oriented permissions required to access DLRS' configuration, including the "Modify All Data" permission?

**Comment by afawcett** [comment]
Yes, the Manage Rollup Summaries page does currently required Modify All Data, due to its internal use of the Salesforce Metadata API (up until very recently the only way to access Custom Metadata in a read and write way). Now that Summer'17 has released a new feature for developers i can look to adopt that in the code. Meanwhile in the current version this requirement still exists.
