### ISSUE TITLE
Salesforce Refresh Instance July 15

### ISSUE THREAD

**Issue by sharstream** [afawcett/declarative-lookup-rollup-summaries#531]
There is any impact with this remote site setting when Salesforce executes the refresh instance?

dlrs_mdapi: https://abbenterprisesoftware--dlrs.na4.visual.force.com

**Comment by sharstream** [comment]
However, I think the action for this case is to redirect a new url instance when the app lets you know automatically when the instance changed. Right?

**Comment by neuranet8** [comment]
We have Declarative Lookup Rollup Summaries Tool (Version 2.9) in our org (attached screen) and there is a remote site setting in the SFDC Setup -> Security Controls -> Remote Site Setting call dlrs_mdapi that is associated with remote site URL - 	https://abbenterprisesoftware--dlrs.na4.visual.force.com

Our SFDC instance (Production) is going to have instance refresh by Salesforce.com this Satursday (July 15, in 2 days, NA4 becomes NA67) so we would like to know what do we need to do to handle this remote site setting for dlrs.

Is the job simply to update the remote site setting to replace na4 with na67 ? If there are other updates or treatment, please reply to this post with the information.

Since the instance refresh is coming in 2 days, any prompt response will be much appreciated.

Thanks.

![dlrs_capture](https://user-images.githubusercontent.com/20980333/28180679-a877ea4e-67ba-11e7-949e-00eebc46c5e5.JPG)

**Comment by DanDonin** [comment]
The remote is only used to auto deploy the triggers. Wait for the instance
move delete the remote setting then go back to dlrs and it will detect that
it is missing the remote setting and ask you to auto set it back up.

**Comment by afawcett** [comment]
NOTE: The remote site is also used by the Manage Rollup Summaries page.

**Comment by afawcett** [comment]
Also @sharstream , also in answer to question, yes, "is the job simply to update the remote site setting to replace na4 with na67"
