### ISSUE TITLE
Rollups on 25 different criteria

### ISSUE THREAD

**Issue by shruthsj** [afawcett/declarative-lookup-rollup-summaries#535]
Hello Andrew,

Firstly i would like to thank you for this amazing tool...

Here is my query.

Im rolling up field value from OpportunityLineItem to Opportunity based on few criteria(Ex; Product Family field values).

I have 25 Product_Family Field values on OpportunityLineItem
25 fields on Opportunity.

For example in OppLine Item when ever the field called Commissionable_Value__c is set to USD 3,000(just an example) and PrdoctFamily is set to APAC_India(Just an Example), kit has to update APAC_India Filed on Opportunity with the value USD 3,000, similarly Based on ProductFamily it has to update relevant field on Opportunity.

Example 2 -  in OppLine Item when ever the field called Commissionable_Value__c is set to USD 3,000(just an example) and PrdoctFamily is set to APAC_Nepal(Just an Example), kit has to update APAC_Nepal Filed on Opportunity with the value USD 3,000,

Do i have to create 25 Lookup Rollup Summaries? or what is the best way to achieve this?

Looking Forward for your kind response.

Thank you,
Shruthi

**Comment by afawcett** [comment]
Hi @shruthsj 

- That is a lot of rollups, you need to be careful with performance here. Do you need them all to be realtime is one question i would ask? If not, review the wiki page on schedule modes.
- I would also check that you cannot use the native platform functionality for rollup summaries, since these objects are in a master delete relationship.
- Finally, you may also want to consider when you need this information and if platform reporting might be a better option? You can also embed platform reports in your layouts for the Opportunity so you can see it per record.

Hopefully this helps.

Thanks,

Andy
