### ISSUE TITLE
precise values generated by DLRS unusable / not rendering in flows

### ISSUE THREAD

**Issue by erezerezg** [afawcett/declarative-lookup-rollup-summaries#552]
Hello,
This may not be an issue directly with DLRS but is definitely related.

- We have a couple of DLRSs calculating averages of certain fields on child records - working as expected. 
- The target fields' types are numbers with 1 decimal spot available.**
- When called inside a flow (meant to render a table on a VF page) these values simply don't show up - neither as numbers nor as a TEXT() formula's output.
- When several types of workarounds are attempted inside the flow (e.g. print the value of that field to a new number variable with any number of decimal spots / using ROUND()/FLOOR()/CEILING()), the flow error that shows up in the debug log is as follows:
_java.lang.String cannot be cast to java.lang.Number_

**I did read up on the Salesforce API holding values more precise than the number of decimal spots defined on their field until edited manually. Once edited manually (cutting off all but one decimal digit) everything behaves as expected.

Is there any way to limit the DLRS to a certain decimal format without using additional fields on the master object?
Any light shed on the subject would be greatly appreciated, and any additional information on the issue will be supplied upon request.
Thanks in advance,
Erez

**Comment by aheber** [comment]
@erezerezg I haven't played with this specifically but my thoughts would be to implement a Workflow Rule or Process Builder that would round the value after DLRS has placed it on the parent record.
I would look at variations of the following, Depending on the behavior you want:
CEILING: https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/salesforce_formulas_cheatsheet.pdf#customize_functions_a_h__CEILING
FLOOR: https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/salesforce_formulas_cheatsheet.pdf#customize_functions_a_h__FLOOR
ROUND: https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/salesforce_formulas_cheatsheet.pdf#customize_functions_i_z__ROUND
You can couple these with multiplication and division in order to change the decimal places that are rounded.

Again, I haven't verified this against your scenario but I have had similar problems and solved them in this way.

Hope that helps.

**Comment by erezerezg** [comment]
@aheber Thanks, that actually solves the issue. I ended up writing a workflow rule to trigger anytime the parent record is edited - with a formula for ISCHANGED() on each of the 13 DRLS average fields inside an OR statement - and that workflow would trigger 13 separate field updates, simply replacing each of those DLRS fields' values with it inside a ROUND(_field_, 1). Obviously I had to be manually fix existing data, but thankfully there wasn't much of that and it does seem to work and behave as expected later inside Flows.

Thanks again.
