### ISSUE TITLE
Getting an error when I try deploying the Apex Trigger and Apex Class to get my DLRS working

### ISSUE THREAD

**Issue by EseU** [afawcett/declarative-lookup-rollup-summaries#553]
I am getting the following error when I try to deploy the Apex Trigger and Apex Class in order to activate a DLRS.

Bellow is the error:

![image](https://user-images.githubusercontent.com/31456178/29854424-ec1aef98-8d13-11e7-96e6-2b2723fa2dfc.png)

Here is the Set up for the DLRS

![image](https://user-images.githubusercontent.com/31456178/29854455-1784f62e-8d14-11e7-888c-73186442a9e4.png)

I'd greatly appreciate any help.

**Comment by afawcett** [comment]
The test code attempts to do an insert into the child object in order to get the platform required test coverage to deploy the trigger. The test code is not that inteligent, so it does not populate any fields, sometimes validation and/or trigger code already on the child object has some requirements for fields that need to be completed. This looks like this case. Have a read of this wiki page on next steps.....  https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage. Sorry for the delay in responding btw, this should get you going and/or at least provide a vanilla (not via the tool) means to reproduce the error and ask for the trigger developers help.
