### ISSUE TITLE
Developer script exception from Enterprise Software : dlrs_pse_Est_Vs_ActualsTrigger : dlrs_pse_Est_Vs_ActualsTrigger: execution of AfterUpdate caused by: System.QueryException: Non-selective query against large object type (more than 200000 rows). Co...

### ISSUE THREAD

**Issue by sharstream** [afawcett/declarative-lookup-rollup-summaries#556]
Apex script unhandled trigger exception by user/organization: 00560000001CgXZ/00D300000001Nm9

dlrs_pse_Est_Vs_ActualsTrigger: execution of AfterUpdate

caused by: System.QueryException: Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact salesforce.com about custom indexing.
Even if a field is indexed a filter might still not be selective when:
1. The filter value includes null (for instance binding with a list that contains null) 2. Data skew exists whereby the number of matching rows is very large (for instance, filtering for a particular foreign key value that occurs many times)

(dlrs)

**Comment by sharstream** [comment]
@cloudbust Christian here is the issue for declarative roll up summary tool reached by github.

**Comment by afawcett** [comment]
Yes, the solution to this issue, is as described in the error message itself. You need to consider a index (added by salesforce support) for the query. This likely due to the filter criteria in your rollup not using indexed fields and/or selective operations. Take a deeper look at this, https://help.salesforce.com/articleView?id=000006007&type=1. Due to this tool being implemented in Apex and thus using SOQL, this is a restriction of the platform and not of the tool. I'll close the issue out for now, but if there is a need to further discuss we can for sure. 👍
