### ISSUE TITLE
Question: how to overcome this error without using Auto Generated trigger? and why the dml contexts of the parent?

### ISSUE THREAD

**Issue by peternoges** [afawcett/declarative-lookup-rollup-summaries#559]
Hi Andrew, i really appreciate your help here. I have 2 questions..

1) **can i activate a dlrs rule without deploying a dlrs "auto-generated trigger" ? If so, how?**
I currently see an error when i try to activate my dlrs rule. 

**The error message is :**  _"Active: Apex Trigger dlrs_someChildObjectTrigger has not been deployed. Click Manage Child Trigger and try again."_   The reason why i **dont want to use the auto-generated trigger** is two reasons: a) i dont like the clutter of dlrs_someChildObjectTrigger when I already have someChildObjectTrigger and b) the fear of the unexpected execution cycles (circular, re-entrant, etc) that may come with having multiple triggers on an object.  The latter is more of a concern.  How would i activate the dlrs rule without using the auto-generated trigger?
I think this is similar to [this issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/309), but i do not have an answer yet.  **In an unsuccessful attempt to fix this:** , i deleted the dlrs_someChildObjectTrigger but  this was not enough to trick your validation because i was still unable to activate my dlrs rule. Next I deployed dlrs_someChildObjectTrigger but simply commented out the call to `dlrs.RollupService.triggerHandler();` and placed the same call within my own someChildObjectTrigger but the rollups were not working the same (despite putting them in the constructor of my all-context-trigger-handler).   What is the cleanest way to use dlrs rollups inside my own triggers? Do I have to use a variety of your global method calls or am i supposed to be able to simply call `dlrs.RollupService.triggerHandler();` from my own triggerhandler? 

2) **design question**
Why does the Auto Generated triggers include a trigger for the parent? Is that to help handle situations where the dlrs children are filtered by some property/field of the parent? In that case I could see why you would need to call RollupService from a parent context. I understand why RollupService needs to be called in child record contexts (for the purpose of updating the parent when child records change).

**Comment by peternoges** [comment]
As i have two triggers on the child object, (one dlrs and one my own), i ran into a SELF_REFERENCE_FROM_TRIGGER error.  I was unsure how to activate the dlrs rule without having the auto-generated trigger deployed. I tried commenting out its call to dlrs.RollupService.triggerHandler();  hoping i could make the call to the same method without my own trigger as discussed here https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/527 but ended up pausing that effort and am keeping both triggers for now.  I did however overcome the SELF_REFERENCE_FROM_TRIGGER error by moving some of my logic out of the beforeupdate context of my trigger and into the afterupdate context of my trigger.  

Can you advise an approach for activating a dlrs rule without using a dlrs-generated trigger? eg i want to use my own trigger handler.  Is it really as simple as calling your global dlrs.RollupService.triggerHandler(); method within the public constructor of my triggerhandler which handles all contexts?  

Thanks for the tips, Andrew!

**Comment by aheber** [comment]
@peternoges I think you might be looking to put this into Developer mode instead of Real-Time. This would allow you to activate the trigger without the deployed code, then you could invoke the rollup from your current trigger setup.

Has been a while since I set one up like this, I could be missing something.

**Comment by afawcett** [comment]
@aheber is correct, select Developer mode on the rollup itself then use the API from your trigger. There are few depending on your needs, e.g. if you have to do your own updates on the master records as well or not. If its the later, you can just use the second one shown below, by passing in Trigger.old, Trigger.new and your object type.

~~~~
global static void rollup(List<RollupToCalculate> rollupsToCalculate)
global static void rollup(Map<Id, SObject> existingRecords, Map<Id, SObject> newRecords, Schema.SObjectType sObjectType)
global static List<SObject> rollup(List<SObject> childRecords)
~~~~

Review the comments above each of the methods above in the code here for more documentation, https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/classes/RollupService.cls

Also regarding "Why does the Auto Generated triggers include a trigger for the parent?", this is due to the parent supporting merge most likely, you can deselect the generation of the parent trigger if this is not a scenario your concerned with.

**Comment by afawcett** [comment]
@peternoges let me know if the above does not get you going, sorry for the late reply. I'll close this issue for now, but we can re-open at any time, np. 👍
