### ISSUE TITLE
Declarative Lookup Rollup Summary (DLRS) lookups wiped - fields showing "N/A"

### ISSUE THREAD

**Issue by fdacruz1** [afawcett/declarative-lookup-rollup-summaries#571]
I just noticed that the lookups that I had set up with DLRS have changed without any input from me. Trying to understand whether or not this is expected behavior.

Specifically: - all of the fields I input information in now only show "N/A" - Description reads: "System managed do not touch".

Furthermore, there are some entries that are showing up as being created by another user. When I asked that user, he stated that he has never used the tool - as expected since I didn't grant access to anyone but myself anyway!

It seems that one of the rollups is working while the others are not.

![screenshot](https://user-images.githubusercontent.com/7267157/31232042-a82ca7a8-a9b6-11e7-9574-07587226a667.png)

**Comment by nishantjadav** [comment]
I think this is because of the new Custom Metadata Type feature in new release.

If you go in to Search and Type Custom Metadata Type, you will find one for rollup summaries. Click on the Manage Records and you will have the list of all your rollups. Samething happened with me when I was searching for my roll ups. I found all the roll ups in Custom Metadata Type. 

Please let me know if you see the same.

**Comment by fdacruz1** [comment]
@nishantjadav - They're all there! (Sorry for the delayed reply - never got a reply notification)

What did you have to do to restore the dlrs triggers? I'm assuming that I'm going to have to go in manually edit the fields so that they contain the information that they should contain.

**Comment by afawcett** [comment]
@fdacruz1 what makes you think you need to restore the triggers? As @nishantjadav has said, just ignore these 'shadow' rollup entries, if your using custom metadata based rollups, just focus on using the Manage Rollup Summaries tab only and don't even look at the Lookup Rollup Summaries tab. 👍
