### ISSUE TITLE
Rollup Calculating on more records than it should

### ISSUE THREAD

**Issue by kschaefges** [afawcett/declarative-lookup-rollup-summaries#577]
I have a rollup summary that is summing information from a child object to the Opportunity.  I'm seeing a lot of errors in the error log for opportunities that have no records in the child object used in the rollup.  Why would these opportunities even attempt to be referenced?  Thanks! Kim

**Comment by afawcett** [comment]
It depends on how you have configured the tool and a current limitation. Basically if your using the realtime mode, you should not see these since calculations are only triggered when child records are edited/inserted/deleted. Likewise if your using the incremetnal schedule mode. However if your using the full schedule calc mode it will likely be passing over all records (depending on your filter criteria). https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups. Does this help?

**Comment by afawcett** [comment]
I will close this for now. But we can keep discussing for sure. Happy to re-open. Thanks. 😄
