### ISSUE TITLE
Possible to reference parent object in relationship criteria?

### ISSUE THREAD

**Issue by JodiNA** [afawcett/declarative-lookup-rollup-summaries#582]
I am trying to do a rollup from Campaign Members to Contacts.

Is it possible to reference a field on the Campaign object in my relationship criteria?  I'd rather not have to create a formula field on the Campaign Member if possible!  

I gave an attempt using the syntax Campaign.MyCampaignMemberField, but I got an error.

**Comment by aheber** [comment]
@JodiNA can you be more specific what errors you're receiving? You can add a related relationship field into the Relationship Criteria box to help filter records. You can not add a related relationship field into the Relationship Criteria Fields because the logic of the tool monitors these fields for change during record save to know when to re-run the rollup. It can't do that for related records because they will not change in the scope of the trigger, they either change before or after from the perspective of the trigger.

Can you give more details on your use-case to help understand how you would want to monitor the parent?

If needed you can leave the lookup relationship in the Relationship Criteria but you run the risk of the rollup being invalid because the parent can be changed without triggering changes on the children, and if that field changes and you re-save the children the DLRS will likely not realize that it needs to recalculate. Even if you pull the value down via formula this will in most cases still be the case. You would have to push it down from the parent with something like Process Builder into a field of identical type in order to fire the save and recognize the value change.

**Comment by aheber** [comment]
Correct, the syntax is correct to reference the field but you can use related records in that field.

As for the calculation accuracy, if you don't anticipate the field to change often you should be fine to just add it to the Relationship Criteria and exclude it from Relationship Criteria Fields. This would allow the system to use it for record filtering but not allow the system to use it to trigger recalculation.

There are two different kinds of scheduled calculations, incremental schedule which uses the relationship criteria fields to know when to put records into a queue that the schedule job will process when it is run. The other type of scheduled calculation is a full calculation, that will run for all records and not just for those which have recorded relevant changes.

I'm pretty sure that is clear as mud. Hope it helps.

**Comment by JodiNA** [comment]
Awesome. Thanks. Makes perfect sense.
