### ISSUE TITLE
classes/dlrs_AccountContactRelationTest.cls (Line: 11: Column:40) : Invalid type: AccountContactRelation

### ISSUE THREAD

**Issue by juanjoseca** [afawcett/declarative-lookup-rollup-summaries#596]
![image](https://user-images.githubusercontent.com/20826761/33736843-baec1584-db59-11e7-95d8-cb6253232a91.png)

Can any body help me out with this?

I have no idea why this is giving me an error message.

Thank you!

**Comment by DanDonin** [comment]
Can you post a screenshot of the DLRS record

**Comment by juanjoseca** [comment]
![image](https://user-images.githubusercontent.com/20826761/33736945-27794ec4-db5a-11e7-8b38-31efcc0aa7bd.png)

Sure 👍

**Comment by juanjoseca** [comment]
So what I'm trying to do is to transfer the active Contact to the Account level. Since we have multiple contacts related to multiple accounts, I'm using the AccountContactRelation Object.

**Comment by DanDonin** [comment]
Huh this is a new object to me. And DLRS is at least on API 37. Are you on
the latest DLRS?

**Comment by juanjoseca** [comment]
I'm using the 2.5 Version right now.

**Comment by DanDonin** [comment]
Try updating I know some older versions had hard coded API names thus
leading to issues with new objects. The newest version has been setup to
dynamically use the newest API via as far as I understand magic ;)

**Comment by juanjoseca** [comment]
Hey So Probably this a dummy question, if I update in production the DLRS, will erase the Roll up records I have created? 😕

**Comment by DanDonin** [comment]
Shouldn't

On Dec 7, 2017 1:15 PM, "juanjoseca" <notifications@github.com> wrote:

Hey So Probably this a dummy question, if I update in production the DLRS,
will erase the Roll up records I have created? 😕

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/596#issuecomment-350096533>,
or mute the thread

**Comment by juanjoseca** [comment]
Thanks for your help @DanDonin! I was able to install the child trigger!
