### ISSUE TITLE
A calculate job is already executing

### ISSUE THREAD

**Issue by lgreer0517** [afawcett/declarative-lookup-rollup-summaries#600]
Hi,
I'm having the same problem as [this issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/491). I was on version 2.7 and upgraded to 2.8 but the problem didn't go away. There are no entries in the Lookup Rollup Summary Logs.  Any help would be greatly appreciated.

Thanks for contributing this tool!
Regards,
Laura

**Comment by DanDonin** [comment]
Look in rollup summary calculate jobs tab. If any records are there delete
them.

On Dec 9, 2017 2:37 PM, "lgreer0517" <notifications@github.com> wrote:

Hi,
I'm having the same problem as this issue
<https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/491>.
I was on version 2.7 and upgraded to 2.8 but the problem didn't go away.
There are no entries in the Lookup Rollup Summary Logs. Any help would be
greatly appreciated.

Thanks for contributing this tool!
Regards,
Laura

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/600>,
or mute the thread

**Comment by lgreer0517** [comment]
Thanks for getting back to me. I did look at the summary logs and there aren't any entries.
Laura

**Comment by DanDonin** [comment]
Not the logs but the "Lookup Rollup Calculate Jobs"

**Comment by lgreer0517** [comment]
Ah, sorry. There are no entries in there either. See screen shot.
![screen shot 2017-12-09 at 6 38 56 pm](https://user-images.githubusercontent.com/34403656/33800567-5930faea-dd10-11e7-80c6-d113ab89eefa.png)

**Comment by DanDonin** [comment]
On the dlrs record there is a field called calculate Id. Clear that field.

**Comment by lgreer0517** [comment]
I don't find any object that has a field called calculate ID. There is a calculate job ID on Lookup Rollup Summary but that object has no records.
Laura

**Comment by DanDonin** [comment]
You might have to add it to the page layout.  I dont think it is there by
default.

API Name dlrs__CalculateJobId__c
Description
Help Text This field is used by the system when using the Calculate button
to track if a calculation job is already running. Clear this field if the
system reports the calculate job is already running and you known this is
not the case.

**Comment by afawcett** [comment]
@lgreer0517 can you check you don't have this field populated on your rollup? If it is and a job is not running please feel free to clear it.

**Comment by lgreer0517** [comment]
Hi,
I'm sorry, I forgot to update you that I had been able to clear the field and I'm all set.
Thank you!
Laura

**Comment by afawcett** [comment]
Excellent @lgreer0517  👍
