### ISSUE TITLE
A way to stop the trigger

### ISSUE THREAD

**Issue by danhowellnz** [afawcett/declarative-lookup-rollup-summaries#601]
I also think this could be built into an enhancement. We are trying to alter the trigger so it doesn't fire when records are created by the api. They are later trigger by a non-dlrs schedule.  

We want to block the trigger from firing if "API_Last_Processed__c" is changed or the record is new. 
However, this code is not working we are still getting   System.LimitException: dlrs:Too many query rows: 50001. Even though all records are new or API_Last_Processed__c is changing 

```
	//don't fire trigger if this turns true
 	boolean apicall = false;   
    
    //check if new
    if (Trigger.isInsert) {
        boolean apicall = true;
    }else{
       //check if any items change
        for (Transaction__c c: Trigger.new) {
            Transaction__c oldTransaction= Trigger.oldMap.get(c.ID);
            if (c.API_Last_Processed__c != oldTransaction.API_Last_Processed__c) {
                boolean apicall = true;
            }
        }
    }
   
    if(apicall!= true)
    	dlrs.RollupService.triggerHandler(Transaction__c.SObjectType);
```

**Comment by aheber** [comment]
@danhowellnz taking a drive-by at this, you are re-defining apicall variable inside of your isInsert test, that scopes the existence of that variable to just that block (between the nearest brackets) and shadows the outer apicall variable that is defined. That means, if I'm understanding right, that your code isn't giving a value to the correct apicall variable and dlrs will ALWAYS run when in insert mode.

That can be fixed by dropping the "boolean" before apicall = true; directly under Trigger.isInsert testing. (line 6 by my count)

I don't know if that will fix all your problems but it will likely solve the problem of deferred processing.

As to the larger problem with query rows, the best answer here is likely working with batch size if you're able. This scenario will be a consequence of many sibling records to your transactions. You have probably already figured all of that out.

**Comment by afawcett** [comment]
@danhowellnz does @aheber observation help? It looks good to me.

**Comment by danhowellnz** [comment]
I managed to get this working. 

The problem wasn't batching it was the 50k error. That's why I thought an enhancement to be able to dynamically turn this trigger off. This is useful when you know it will hit limits is useful or in my case I never want this trigger messing up a one time api call. 

The problem with the schedule is that it has the same limits and tries to process everything. I use the declarative scheduling tool to just process the records I know need to be updated.

**Comment by afawcett** [comment]
Thanks @danhowellnz for the update. Note that the latest update does include improvements for the full recalc scheduled mode to avoid updating records that do not need it. However your approach will also work if you can create the criteria.
