### ISSUE TITLE
Issue Upgrading to 2.10

### ISSUE THREAD

**Issue by daveerickson** [afawcett/declarative-lookup-rollup-summaries#612]
I'm having an issue upgrading from 2.9 to 2.10. It is throwing an error that 'The user license doesn't allow Assigned Apps'. I'm pretty sure this is due to applying this permission set to customer portal users, and that license type does not allow assigned apps.

The source in this project doesn't have a change to either of the permission sets so I'm not sure why it is changed. Further neither of the permission sets have applicationVisibilities tags which compounds my confusion. Maybe I'm completely missing something on how the Assigned Apps are actually assigned.

May I also suggest that including the 'Declarative Lookup Rollup Summaries Tool' app for users that are not configuring the app may not be desirable. It's one more app that'll show up and clutter their view. In fact if it's not needed maybe the tabs visibility could be removed from the read only permission set.

**Comment by afawcett** [comment]
Yeah it is odd, there was once an earlier version where the perm sets shipped with a specific license set on them, but i resolved that. Now they have no licensed defined, so should not be restricted. Also as you say i am also struggling to see what has changed to cause this. Is the error on install or use btw? 

Meanwhile, yeah i will mark this as an enhancement to remove the app from the process rollups permission set, though tbh its not really needed since i relaxed the checking in the code to respect more of a system mode execution of the rollup calcs. So you could just try without it.

**Comment by daveerickson** [comment]
I revisited updating DLRS from 2.9, now to 2.11, and received the same error. As you suggested I was able to remove the perm sets from customer portal users without any ill effect. I was then able to update the package once the perm sets were removed. So, in effect this issue is solved as the perm set isn't a requirement for DLRS to run. Thanks!
