### ISSUE TITLE
Avoid Shadow Custom Object Based Rollup Records - Total DLRS Newbie frustration

### ISSUE THREAD

**Issue by Scubafiend** [afawcett/declarative-lookup-rollup-summaries#618]
I did not install DLRS, it was here when I came on board.  A prior admin created 22 Rollup Summaries and that would be great - Except - On every single one of them all of the fields except the Name, Owner, Created by and Description fields are all blank or have N/A. The Description only says "System managed do not touch". 

I can see by the Summary of Schedule items and the name what it is doing, but I have no way to make any changes to it. I suspect she wrote Apex code but can't figure out why create a Lookup Rollup Summary in DLRS AND create Apex code??? It was my understanding that the whole point behind DLRS was to avoid writing a bunch of Apex code....

I'm a SysAdmin and have a background in SQL but I'm just getting started in Apex. I'm reading everything I can get my hands on about DLRS, but I would appreciate any suggestions or insight into this!

**Comment by aheber** [comment]
@Scubafiend hopefully we can help and get you on your way.

The definitions for an individual rollup come in two flavors, the original data records using custom objects and the more recent Custom Metadata. Depending on when these were added to your system and what version you're on would help inform how yours are defined. I will mention that the tool still supports both setups, just that newer installs are encouraged to use Custom Metadata.

If you navigate to the All Tabs in salesforce (Classic the + and Lightning Exp the 9 dot grid). To look for Custom Metadata type rollups you can find the Manage Lookup Rollup Summaries entry. In the drop down at the top of the page you should be able to list and review configured rollups, anything with an "Active" should be running.

If you have the older style you'll see the Lookup Rollup Summaries tab to see anything configured. 

The two types of records generally behave the same, and the tool will still run both of them concurrently (I have some of both right now).

If you've already gotten through this and that is where you're saying you see the blank fields then DLRS isn't running. If the fields are blank then it isn't running because those are its configuration settings. If you're getting rollups on these records then it would be sourced from something else in your system.

Once you can confirm that you've gotten this far, if you still need help can you send screenshots?

Also, you can review the debug logs in your org to see if the data is modified when DLRS is running or as part of some other area of the configuration or system.

Hope that helps to guide next steps.

**Comment by aheber** [comment]
Looks like this was fixed in the Community:
https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p&fId=0D53A00003P6A4c

@Scubafiend can you confirm?

**Comment by afawcett** [comment]
@Scubafiend sorry for the frustration. As @aheber has pointed out, you are experiencing some fallout from the tools evolution from defining rollups in one place and now another. The old place still needs (for some internal reasons) to be kept in sync (to a lesser degree) with the new place. If you solely use the Mange Rollup Summaries tab and not the Lookup Rollup Summaries tab you will be fine and the system keeps things in check. However, i can imagine if you are inheriting this tool config form another admin its confusing to know which place to go for the source of truth. I am going to flag this as an enhancement and see if i can avoid the tool needing to have these 'shadow' records. You are not the first to be confused. Ideally, i would like to get rid of the older way of doing things, but i suspect its still in use by a lot of installs. Thanks again and hope this goes some way to explaining the background. 👍

**Comment by Bard09** [comment]
We're seeing that on several of our environments, the DLRS 'system managed do not touch' Custom Object records aren't always a 1:1 match with the equivalent fields set up in DLRS Custom Settings.... and we are wondering if this is causing DLRS processing to run 2x?  or possibly run incompletely?

Also, if we 100% use the Custom Setting to manage DLRS, but went in and deleted the 'system managed do not touch' records-- what would happen?  Would they be rebuilt?  (I'm wondering if this is a way to get everything to match up)

**Comment by afawcett** [comment]
Yes they would get rebuilt. Also the shadow records do not need to match the field values of the associated Custom Metadata counterparts. The only reason they exist is to support logging.

**Comment by afawcett** [comment]
Fixed in v2.12
