### ISSUE TITLE
Child Trigger Error

### ISSUE THREAD

**Issue by jpellicano1** [afawcett/declarative-lookup-rollup-summaries#621]
Getting the following error:
![image](https://user-images.githubusercontent.com/28963892/35350349-a0450006-010b-11e8-9af1-8bd1f748fab3.png)

> dlrs_OrderTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, blng.OrderTrigger: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object Class.blng.CommonConstant: line 257, column 1 Class.blng.OrderDomain.handleBeforeInsert: line 117, column 1 Class.blng.TriggerManager.triggerHandler: line 123, column 1 Class.blng.TriggerManager.triggerHandler: line 48, column 1 Trigger.blng.OrderTrigger: line 16, column 1: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_OrderTest.testTrigger: line 11, column 

Is that an issue with the DLRS or the BLNG managed package?  Any way around it?

**Comment by afawcett** [comment]
This is an issue with lack of robustness in the BLNG trigger when field values are not completed. The generated test code for the DLRS trigger you are deploying does not attempt to fill field values in (it does not know the object particulars). You can read more about this and what to do about it here. https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

**Comment by cumulus-robert** [comment]
I am having a problem with this also ... I'm attempting to deploy DLRS and am getting attempt to de-reference null object on an already existing trigger:

Error when attempting to activate DLRS:

dlrs_OpportunityTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, OpportunityTrigger: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object Trigger.OpportunityTrigger: line 10, column 1: [] Class.dlrs.RollupService.testHandler: line 277, column 1 Class.dlrs_OpportunityTest.testTrigger: line 11, column 1

Trigger reference is just a handler type trigger (note all our trigger look like this and we have DLRS used across board):

```
trigger OpportunityTrigger on Opportunity (after update, before update, before insert,after insert) {

    OpportunityTriggerHandler OHandler = new OpportunityTriggerHandler();

    OHandler.NewO = (List<Opportunity>) Trigger.new;
    OHandler.OldO = (List<Opportunity>) Trigger.old;
    OHandler.oldMap = trigger.oldMap;
    OHandler.newMap = trigger.newMap; 
    OHandler.IsBefore = Trigger.IsBefore;
    OHandler.IsAfter = Trigger.IsAfter;
    OHandler.IsUpdate = Trigger.IsUpdate;
    OHandler.IsInsert = Trigger.IsInsert;
    OHandler.IsDelete = Trigger.IsDelete;
    OHandler.IsUnDelete = Trigger.isUnDelete;

    OHandler.process();

}
```

It appears to be failing on the before insert function. Why would attempting to set this value from trigger function be null?

**Comment by cumulus-robert** [comment]
I figured this out,I wasn't getting multiple errors, only this one. Turns out turning off record merge function fixed my issue. I do have a helper class I use in DLRS, but because ContactTrigger was failing, this one was also. I created another help ticket on how to add test helper data on parent triggers. My understanding the test helper data only works on child triggers.
