### ISSUE TITLE
dlrs:Too many SOQL queries: 101

### ISSUE THREAD

**Issue by ashleyleifer** [afawcett/declarative-lookup-rollup-summaries#629]
Error received which is hindering processing of other flows and not able to create opportunities. 

org has 145 DLRS, what the best way to process so that we aren't running into this error? Should I set all to Scheduled and do I just need to create one scheduled job with referencing the apex class RollupJob?  currently in the org there are about 45 scheduled jobs all referencing the apex class RollupCalculateJobSchedule... Thanks!

BTW already read this but doesn't fully answer our issue https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups

**Comment by afawcett** [comment]
Yes, the best way is to split some or all into schedule mode. The tool does try to reuse queries between rollups, but with that number and likely variance in criteria (which prevents the query reuse from working effectively) its hard for its optimization to be completely successful in all honesty.

I have updated the wiki page to clarify that schedule entries using the class RollupCalculateJobSchedulable relfect the use of [Scheduled Full Calculate](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups#scheduled-full-calculate) for a given rollup. You can review the Job name to determine the ID of the Rollup then enter this in the URL (later versions of the tools did make this is easier to reconcile by rollup unique name if specified). 

If you already have a lot of scheduled jobs, yes, moving to **Scheduled Full Calculate** will not only use up a lot more of these slots, but (depending on the use of criteria) is quite expensive resource wise. I would consider using the [Scheduled Incremental Calculate](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups#scheduled-incremental-calculate), as this uses only one slot and only recalcs based on the child records changing between runs.  Hope this helps.

**Comment by DanDonin** [comment]
Quick question of clarification!  So when you say variance in criteria you
only mean the relationship criteria (the WHERE in the SOQL it builds) not
in the aggregated field correct?

**Comment by afawcett** [comment]
@DanDonin yes... mostly.... though combos like COUNT rollup, plus a CONCAT rollup will generate a new query as the code uses to entirely different approaches, since CONCAT is not native to SOQL. However, if the criteria match between a roll-up having COUNT and another having SUM the tool attempts to accomplish this with one query.

**Comment by ashleyleifer** [comment]
Thanks Andrew! For my client that has 154 DLRS with most child on the opportunity I have set everything to calculation mode scheduled and we aren’t getting SOQL errors anymore.  

Best Regards, 
Ashley

**Comment by afawcett** [comment]
@battarro  is it possible you have some recursion here? DLRS will do minimal queries for rollups in scheduled mode, just to check the mode of the rollup, hence the selectActiveByChildObject code is run. This runs once for each DLRS trigger invocation... if you grab the debug logs i would wager you see a lot of DLRS trigger calls... maybe due to recursion and/or non-bulkified inserts to the child object DLRS is monitoring? Maybe?

**Comment by afawcett** [comment]
@ashleyleifer let me know if you want to re-open, will close for now.
