### ISSUE TITLE
Look Up Field

### ISSUE THREAD

**Issue by bribrisnook** [afawcett/declarative-lookup-rollup-summaries#633]
Hello! Just getting started with DLRS and I cannot figure out how to get the rollup to show up in my Aggregate Result Field. Is the Aggregate Result Field supposed to be a specific format? Mine is currently a number field and I am counting the records of Tickets created however, nothing is showing up in that field on the project. 

Thanks!

**Comment by aheber** [comment]
@bribrisnook could you post a screenshot of your setup for this DLRS job? If there are custom objects involved maybe share some of how the child and parent are related to each other. That would help us to better help.

Thanks!

**Comment by bribrisnook** [comment]
![testlookup](https://user-images.githubusercontent.com/36423371/36217507-e1267f3c-116e-11e8-857a-8689493c07c9.png)
So the Parent object is a custom object Project that the child object 'Ticket' looks up to. When a user creates a Ticket they have three different ticket types; Risk, Change Request, Issue. We are only wanting to count the records on the Ticket object that are Risk tickets. On the parent object I created a number field called 'TicketRollUpLookup'. When I create a new risk ticket that field is still not populating though and I can't figure out why it won't pull the records. 

Thanks.

**Comment by bribrisnook** [comment]
I believe the issue is coming from the 'Relationship Criteria' because once I got rid of it, the field was populated. However, the relationship criteria is needed for this roll up. Is there any hints on the relationship criteria?

Thank you!

**Comment by DanDonin** [comment]
You don't need to put the FK field in the relationship criteria fields box.
Also when counting it is better to count IDs. That soql looks correct have
you tried to query the DB and see if it returns results for that query?




On Feb 14, 2018 9:12 AM, "bribrisnook" <notifications@github.com> wrote:

[image: testlookup]
<https://user-images.githubusercontent.com/36423371/36217507-e1267f3c-116e-11e8-857a-8689493c07c9.png>
So the Parent object is a custom object Project that the child object
'Ticket' looks up to. When a user creates a Ticket they have three
different ticket types; Risk, Change Request, Issue. We are only wanting to
count the records on the Ticket object that are Risk tickets. On the parent
object I created a number field called 'TicketRollUpLookup'. When I create
a new risk ticket that field is still not populating though and I can't
figure out why it won't pull the records.

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/633#issuecomment-365677742>,
or mute the thread

**Comment by afawcett** [comment]
@bribrisnook let us know if the awesome support you got from @aheber and @DanDonin here helped or not. I will close the issue, but we can for sure re-open as needed. Thanks!
