### ISSUE TITLE
Rollup count of events on contact errors out

### ISSUE THREAD

**Issue by jmmurphey0317** [afawcett/declarative-lookup-rollup-summaries#655]
I have a rollup setup to count the number of events related to a contact, the permissions and naming are all correct but it still errors out
![event_error](https://user-images.githubusercontent.com/34921158/37464947-da3b141a-2827-11e8-8d4c-8a73c73b9db1.png)
![2018-03-15 08_06_31-lookup rollup summary_ contact events salesforce - enterprise edition](https://user-images.githubusercontent.com/34921158/37464955-dd9b9300-2827-11e8-84e8-b85781ed67fe.png)

**Comment by jmmurphey0317** [comment]
@afawcett

**Comment by jmmurphey0317** [comment]
So i just realized something, it works in classic but not lightning

**Comment by afawcett** [comment]
So DLRS is having an issue due to some code in Apex class HFT package, class HexaFieldTrackerUtils method createFieldHistory. If you go an make the same edit to the parent record DLRS is attempting to update (per the rollup definition in play) in manually way i suspect you will see the same error. Can you try this? You can also ask the author of the HFT package (see Installed Packages under Setup) to comment on this.

**Comment by RobertGAlexander** [comment]
Could this error be occurring because the API version of that HexaFieldTrackerUtils class is 39 and the latest version is 45?

![image](https://user-images.githubusercontent.com/7397327/54647608-5da63400-4a60-11e9-9979-bd97af0d8555.png)

**Comment by afawcett** [comment]
@robertgalex thanks for sharing. Wondering how that class is related though?

**Comment by afawcett** [comment]
@robertgalex let me know if you still want to discuss and we can re-open
