### ISSUE TITLE
Suppress error messages?

### ISSUE THREAD

**Issue by toddkadas** [afawcett/declarative-lookup-rollup-summaries#663]
![dlrs_error](https://user-images.githubusercontent.com/38049067/38266069-86d0ae84-372c-11e8-8f3d-3a1202e9e706.PNG)

Hello and thanks in advance for your help! This tool has been a lifesaver and I wouldn't know how to thank you enough for it.  The only small issue I'm wondering if possible to resolve is that of error messages.  In attached screenshot, user encountered error message while creating an opportunity due to validation rule on account that requires that he enter a complete address.  That is our expected and normal behavior and user should receive error message indicating City is required (on Account).  However, the rest of the text is all thrown from DLRS.  Is it possible to remove that? 
Thanks again and hope to hear back from you soon

**Comment by afawcett** [comment]
It should not show stack traces of the code if you have managed version of the package installed (see README for those links). So i am assuming you have the unmanaged (raw code) deployed into your org? Was this due to a desire to customize the code for your own needs? Anyway, the net is you cannot remove this as far as i know since the system is viewing it as your "code" in your org and feels that you need more info (i know its not ideal). The solution would be to switch to the managed version of the tool (the platform hides the packaged code and stack traces in this case). However.... migrating from unmanaged to managed is going to be very very painful... long story short... you have to put up with it without a lot of re-implementation work to switch to the managed version of the tool.

**Comment by lachlanburnside** [comment]
Hi there,

I've just started with this tool and it looks amazing! However, I'm having the same error with a managed installation. Do you know why this could be?
