### ISSUE TITLE
Unable to connect to the Salesforce Metadata API.

### ISSUE THREAD

**Issue by PaulTest** [afawcett/declarative-lookup-rollup-summaries#684]
Hi,

 I am using declarative roll up in a developer sandbox. I have used it recently in production for an unrelated roll up with no issues but now I am trying to create a roll up field for a custom object from the Asperato managed package. When I go to deploy the trigger I get this error: "Unable to connect to the Salesforce Metadata API."

What do you think might be causing this?

Thanks 

Paul

**Comment by vpichet** [comment]
Hi, I have the same problem. I get the following error: 

DEBUG USE ONLY: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

**Comment by afawcett** [comment]
Have you reviewed, https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues?

**Comment by atbryant** [comment]
I'm having the same issue. First time I've seen this error.

I've deleted the created Remote Site and creating a new one, tried it in Lightning and Classic, and still receive this error. I am on a custom domain in Sandbox; is there a different remote site I should be using?

**Comment by kelseyingram392** [comment]
I'm also on a custom domain in a regular Sandbox, and haven't been able to connect to the metadata API at all.  I disabled the "Lock sessions to the IP address from which they originated" setting in Session settings, tried uninstalling and reinstalling and am still getting the same error message. Are there any other known settings that I should check?

Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

**Comment by doomsday-fragile** [comment]
i have disabled the session lock settings in the session settings but still getting this error

**Comment by kfeng86** [comment]
I'm also still getting this error. Here's what I did:

1. Installed 2.11.1 and tried to create remote site setting
2. Got the error of "Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor="
3. Went into Setup and unchecked Lock Sessions to IP and then deleted the remote site setting
4. Went back to create the remote site setting
5. Same error
6. Uninstalled the package and deleted the remote site setting
7. Installed 2.11 and tried to create the remote site setting
8. Same error

I am out of ideas except that I'm also having OAUTH errors trying to install something from appexchange and wondering if this is because it's a really old org. (Sorry I'm not a developer so I'm not even sure where to look to debug this).

Any help would be greatly appreciated!!!

PS - Andy - saw your session at Cactusforce in AZ a few weeks ago: great job! (it totally went over my head, but I got the gist of the session).

**Comment by jimhubert** [comment]
I have the exact same issue that @kfeng86 described above,  Any help to resolve this would be appreciated, as I am stuck!

**Comment by jimhubert** [comment]
I got a recommendation from @JimBTek on a different thread to look into Custom Metadata access changes that Salesforce has released in Spring '20.  Now for users to access Custom Metadata (Which is vital to DLRS), you need to give users access to the specific Custom Metadata via their Profile or a Permission Set. 

It looks like that was the problem, as making the custom metadata changes recommended by Salesforce at https://releasenotes.docs.salesforce.com/en-us/winter20/release-notes/rn_forcecom_development_custom_metadata_require_cruc.htm solved the problem for me.

**Comment by kfeng86** [comment]
So obvious! Yet so not (everytime I update the conga metadata settings for clients, I see and ignore the DLRS one- duh!). Thanks @jimhubert !!!

**Comment by afawcett** [comment]
Looks like we have a solution here. Also I have made some changes to the latest version to avoid the need for remote site (if my domain is used in the org) so this should also help. 👍

**Comment by rrobinsoncpa1** [comment]
I followed the steps outlined above, and am still receiving the error message. Not sure where to turn next.

**Comment by afawcett** [comment]
Improved this experience and new Wiki page - see v2.13 release notes here https://github.com/afawcett/declarative-lookup-rollup-summaries#packaged-release-history
