### ISSUE TITLE
First error: [null] AsyncApexExecutions Limit exceeded.

### ISSUE THREAD

**Issue by lauramccraven** [afawcett/declarative-lookup-rollup-summaries#685]
I scheduled a bunch of roll-ups and they all failed with this error. 

First error: [null] AsyncApexExecutions Limit exceeded.

Is this because I ran too many of them at one time or will even one fail because we have more than 10000 records?

**Comment by slhyatt77** [comment]
I can confirm that the issue is with the size of the parent object.  Every rollup that we have where the parent object is Account or Contact is failing with this error.  The Account object has 327,934 records and the Contact object has 512,874 records. It appears that the DLRS code does a non selective query on the parent (ex. "Select Id From Account").  This will always error on an object over 100,000 rows.

It would be awesome to have a way to filter down the parent object on the roll up record just like you can when you manually calculate.

**Comment by afawcett** [comment]
When you scheduled a full calculate you can express filter criteria. The field shown for filter criteria is for the parent object. Let me know if this does not work. Thanks.

**Comment by svanreisen** [comment]
I also get this error. I thought it had to do with a org limit, DailyAsyncApexExecutions: Max: 250000
Remaining: 64908 (for me at this moment)  This "remaining" number varies throughout the day, depending  on the jobs that have been processed.  One DLRS job in my org seems to absorp about 4800 apex executions.

I would like to get rid of this error, so I would like to try the filter. However, I have not found a clever way to define a filter yet. For instance, I have payment records that I want to sum in the contact record (= parent).  But as I do not know upfront for which contacts I have new/changed payment records, I need to have DLRS check all contact records (and payment records).  If the filter would run on the child (payments), I could filter on for instance "last modified=last 7 days".  Would you have a suggestion as to what filter I could apply to the contact record?

**Comment by ashwinjangam** [comment]
Hello Andy,
I am also getting this error
Apex script unhandled exception by user/organization: (Organisation ID)

Failed to process batch for class 'dlrs.RollupCalculateJob' for job id '7070X0000C09xiA'
Could you please help me.
Thanks

**Comment by afawcett** [comment]
@ashwinjangam you seem to be trying a few places to contact me here! ;-) As I said in my other places, this is a shared limit by all code in your org. Please review Setup menu under Apex Scheduled Jobs and also Setup > Apex Jobs to see what else is running so often.
