### ISSUE TITLE
Realtime not working

### ISSUE THREAD

**Issue by ladykb27** [afawcett/declarative-lookup-rollup-summaries#732]
Hi,  I have a rollup set to realtime but it does not work, when I change to schedule every 24 hrs it works fine..

There are formula fields used in the rollup is this the issue for realtime?

**Comment by aheber** [comment]
@ladykb27 could you post a screenshot of your config and possibly the configuration of the formula fields?

If the formulas reference outside of the object through lookup fields then it is very likely that the realtime isn't firing when the formula is changed because the changes happened on the related records and not on your child records. In this case full scheduled will work but nothing else will see the change as a result of the triggers so they won't know the values should be updated.

**Comment by ladykb27** [comment]
Hi I will do this but worth mentioning that it seems to recalculate when its ticked, but it doesnt recalculate when its unticked... this being a ticked formula field

**Comment by timmy2cakes** [comment]
Please can someone help me here I'm not getting any response on this #733

**Comment by afawcett** [comment]
@ladykb27 as @aheber pointed out its likely your formula fields. DLRS cannot see these changing. Please add the fields your formula field uses into the Relationship Criteria Fields field to make it see those fields. This should help. Let us know if not and we can re-open.
