### ISSUE TITLE
Problem with Delete/update records at child object

### ISSUE THREAD

**Issue by maayana12345678** [afawcett/declarative-lookup-rollup-summaries#773]
when I try to delete a record i get the message: "

Validation Errors While Saving Record(s)
--
There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger dlrs_TransactionTrigger caused an unexpected exception, contact your administrator: dlrs_TransactionTrigger: execution of AfterDelete caused by: System.UnexpectedException: field 'Account_ID__c' can not be grouped in a query call: Class.dlrs.LREngine.QueryExecutor.query: line 662, column 1"."

same as when I try to update a record

**Comment by MikeVenman** [comment]
Hi there. I'm experiencing the same issue as above.  I've checked that my fields are accurate, here are is the error I'm getting.

Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger dlrs_Unique_Selling_ConversationTrigger caused an unexpected exception, contact your administrator: dlrs_Unique_Selling_ConversationTrigger: execution of AfterInsert caused by: System.SObjectException: Illegal assignment from Integer to String: Class.dlrs.LREngine.rollUp: line 263, column 1

I've checked that my fields are accurate, but I was hoping you could help point me in the right direction.  Thanks.

![image](https://user-images.githubusercontent.com/40805804/57490338-8687c000-727e-11e9-9c64-f6b2dc498773.png)

**Comment by DanDonin** [comment]
Sounds like the field you are rolling into is a string field.

**Comment by MikeVenman** [comment]
Thank you @DanDonin that worked!
