### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by Shraddha-Ingale** [afawcett/declarative-lookup-rollup-summaries#795]
![image](https://user-images.githubusercontent.com/35553420/53087303-cc10d880-352c-11e9-8e14-f14fd5d5e665.png)
Trying to upload DLRS triggers, without before events.
Tried with redeploying trigger and test class. Still facing same issue..

**Comment by aheber** [comment]
@Shraddha-Ingale could you provide some insights on any other errors experienced during the deploy? 
It sounds like you've modified the trigger to remove the `before` handling, is there some reason for that? I get the feeling your test scenario is breaking as a result of that decision. You will likely need to write custom tests to accommodate that decision as well as ensure you're not missing other times in the record life-cycle where DLRS would need those events. (I haven't reviewed to see when those are)

**Comment by afawcett** [comment]
@Shraddha-Ingale yes, i also have the same feeling as @aheber here. Also some docs on custom test code (DLRS only generates very basic test code). It maybe that when the DLRS triggers where first deployed coverage was fine, but since things changed with related objects/triggers. https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage. Let us know if you want to re-open this issue btw. 👍
