### ISSUE TITLE
Possible to reference Campaign field in relationship criteria?

### ISSUE THREAD

**Issue by nrustigi** [afawcett/declarative-lookup-rollup-summaries#796]
I am creating a rollup from Campaign Member to Contact. Can I reference a field in Campaign? Campaign.Type = 'Board Meeting' is what I have and doesn't seem to be changing the outcome after removing and redeploying the code.

**Comment by aheber** [comment]
@nrustigi you can certainly do that, I do it all the time. You shouldn't need to redeploy the trigger to make it work. The only gotcha with that scenario is that if the Campaign.Type value changes it will not force a recalculation because only changes on the local record can be monitored. You will also not be able to add the field to the Relationship Criteria Fields as it isn't a local field.

When you made the change did you perform a full recalculation on your data to propagate the new settings?

**Comment by nrustigi** [comment]
@aheber part two of this:

I am using DLRS to summarize a Contact's attendance at a different events/campaigns (separated by campaign types). On the contact, I have percentage fields that DLRS populates. The issue is that if a person never invited to an event of x campaign type, they still get a 0%. I'd love to somehow keep that null to show that the person was never invited to that type of campaign.
