### ISSUE TITLE
Performing relationship criteria on parent object field

### ISSUE THREAD

**Issue by ASanso80** [afawcett/declarative-lookup-rollup-summaries#799]
I have a relationship criteria expression that is as below -

(Date1 > Date2) AND (Type = 'TEXT' OR Type = 'TEXT')

Date1 is a date field on records in the child object
Date2 is a date field on records in the parent object
Type is a text field on records in the child object

So I am looking to sum values into a field on the parent object record, from a field on related child records, where a date on the child object is greater then a date on the parent record, and the type matches two variables.

My problem is in referencing the date on the parent objects record. I have tried -

Relationshipfield__c.Date2__c
Relationshipfield__r.Date2__c
Relationshipfield.Date2

to no avail. Hope that's easy enough to understand.

Thank you.

**Comment by aheber** [comment]
@ASanso80 SOQL doesn't allow relative comparisons (field A compared to field B). To accomplish your goal you'd need to add a formula field to the child record and evaluate the formula field in your Relationship Criteria.

Please keep in mind that DLRS has to be triggered by something. If you change the date on the parent record it won't automatically trigger DLRS on the children to recalculate the value. I usually recommend setting up a realtime job for that and either pushing the date down to all the children records or having a full recalculation scheduled on a regular enough bases to ensure that values are mostly up to date.

**Comment by ASanso80** [comment]
Thank you, I had explored this suggestion but considered it to be not possible, I might be wrong.

If the date field on the parent object was changed, I would need the formula in the child object to recalculate. So taking DLRS out of the equation, would the formula field on the child record update if the date in the parent record was changed?

Regarding DLRS it was my intention to perform a scheduled recalculation overnight each day.

**Comment by aheber** [comment]
One thing to keep in mind is that formula fields don't have a value until you inspect/query the value. A change in the value a formula field would return does not trigger DLRS to perform a real-time calculation because the database wasn't updated with the value and can't queue a record for a regular scheduled calculation. For those things you need a change to be saved on the child record. Still, the only way to compare fields is in a formula.

Understanding that then you have to choose between building up the system enough to get realtime calculation or accepting the values to fall out of sync and being pulled together periodically.

For real time you can write a Process Builder/Trigger that when the date changes on the parent, push that down to the child as a field update. This action will be able to fire up DLRS and perform the calculation, still filtering on the formula field. This would be the best way to achieve real-time calculation.

If you can't do that then you need to understand that DLRS can't keep you up to date on its own. Now you need some outside stimulus to start the DLRS calculation for ALL records (because DLRS can't easily know what has changed and can't limit itself to only those records). This excludes the normal scheduled job and requires putting the job in Process Builder mode and scheduling a full recalculation on a regular basis. Depending on the number of records this can be a significant effort for your org to accomplish but would be the best way if you can't "know" which records needs to be processed.

If that isn't very clear let me know and I can come up with another way to describe it.

**Comment by ASanso80** [comment]
Thank you very much for your advice, it certainly is helpful and I believe I have understood correctly, but worry I haven't communicated the problem well enough.

> Understanding that then you have to choose between building up the system enough to get realtime calculation or accepting the values to fall out of sync and being pulled together periodically.

Pulled together periodically - To be specific, I want the calculation to run overnight per day, the update of the formula field in the child object (which compares the dates in child and parent object) and then the DLRS rollup based on the results of the formula field. I do not need the formula field on the child object to be realtime, nor the DLRS rollup. I just need the formula on child object to be recalculated one time ahead of the scheduled overnight DLRS rollup, even if the date on the parent object is updated 20 times that day, doesn't matter, because only the most recent update at Close of Business counts.

The only barrier we have is what would trigger the formula update on the child object ahead of the scheduled DLRS rollup.

> For real time you can write a Process Builder/Trigger that when the date changes on the parent, push that down to the child as a field update.

Great suggestion, but we would potentially be updating thousands of child records per trigger, multiple times per day. 1 Parent record would have likely 90-120 child records to update, and we have 2-300 parent records where the trigger is being fired 3-4 times per day.. it would scale up exponentially over time, and that level of traffic concerns me.

So the only problem I have is how to update the formula field on the child object one time, each evening, ahead of the DLRS rollup.

**Comment by aheber** [comment]
I think we're on the same page. I think the biggest thing I could tell you now is that if you have built the formula field on the child and it references the parent then it is always "updated." Formula fields don't have a stored value so there is nothing to update. Their value is calculated at the exact moment that you execute the SOQL to retrieve or filter on them. 

I believe you're good to go with a daily recalculation and having the formula field in your Relationship Criteria field on the DLRS configuration. From there you will set the DLRS in Process Builder mode and have a full calculation scheduled daily.

**Comment by ASanso80** [comment]
Thank you! Your advice has been excellent, will get this in place today.
