### ISSUE TITLE
Any pointers on the Apex Error: pse:Too many queueable jobs...

### ISSUE THREAD

**Issue by eggletm** [afawcett/declarative-lookup-rollup-summaries#846]
Hi
I have deployed DLRS in a Sandbox environment however the first rollup I have created is failing:
In the Apex Jobs the Apex Class "RollupCalculateJob" is running and comes up Completed with 1 Failure, the Status Details message is:
First error: pse:Too many queueable jobs added to the queue: 2
The rollup is on the Resource Request Object

The environment did have Rollup Helper installed, which had triggers installed on the Account & Opportunity Objects. I have subsequently uninstalled Rollup Helper and I am still receving the above error.

Any thoughts?
Thanks

**Comment by afawcett** [comment]
This is a problem with the pse trigger, it needs to know when its running async and not attempt to enqueue a queueable job. This is happening because you have a DLRS running in async mode that inserts/updates Resource Request object which in turn has its own packaged trigger on it that tries to enqueue a queueable job. You need to speak to the vendor of the package this trigger belongs to.
