### ISSUE TITLE
CaseTrigger: execution of AfterInsert caused by: System.SObjectException: Invalid field Account for Case (dlrs)

### ISSUE THREAD

**Issue by MariaHuemmer** [afawcett/declarative-lookup-rollup-summaries#849]
Hi, I'm running into this error when I aggregate Cases to Account.

CaseTrigger: execution of AfterInsert caused by: System.SObjectException: Invalid field Account for Case (dlrs)

The error occurs for System Administrators as well as end users. This is in a Summer 19 sandbox

Here's what I have set:
Parent Object: Account
Child Object: Case
Relationship Field: AccountId
Relationship Criteria: RecordType.name = "Support" and isclosed = False
Field to Aggregate: Id
Aggregate Operation: Count

Any ideas?

**Comment by odedbre** [comment]
It looks like I have the same problem, trying to count how many Cases a Contact has:
Parent Object: Contact
Child Object: Case
Relationship Field:  Contact

Apex trigger dlrs_caseTrigger caused an unexpected exception, contact your administrator: dlrs_caseTrigger: execution of AfterInsert caused by: System.SObjectException: Invalid field Contact for Case: Class.dlrs.RollupService.handleRollups: line 908, column 1

**Comment by afawcett** [comment]
This could have been an error in the platform at the time. Let me know if your still getting it.
