### ISSUE TITLE
Test coverage issue when trying to deploy child trigger

### ISSUE THREAD

**Issue by ktallman** [afawcett/declarative-lookup-rollup-summaries#912]
**Describe the bug**

Error:dlrs_workstudy_EmploymentTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, workstudy.cr_employment: execution of BeforeInsert caused by: System.QueryException: List has no rows for assignment to SObject Class.workstudy.cr_mgr_employment.createEmploymentName: line 20, column 1 Trigger.workstudy.cr_employment: line 3, column 1: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_workstudy_EmploymentTest.testTrigger: line 11, column 1
--

Warning:
dlrs_workstudy_EmploymentTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

**To Reproduce**
1. Go to new rollup calculation
2. Click on Manage Child Trigger then click on Depoy
3. See error

**Expected behavior**
The trigger should have been deployed

**Screenshots**
![DLRS trigger error](https://user-images.githubusercontent.com/9255428/75053818-c1ae5500-5486-11ea-8384-fad08c23709e.jpg)

**Additional context**

**Comment by afawcett** [comment]
Hi @ktallman the root error is not this tool it is that the test data the tool generats cannot predict the required fields for your child object. Because of this one of the other triggers on this object is failing, i have extracted the part of the error below. You have two options, fix the trigger so it tolerates null values in the object or enhance the test code this tool generates. This can be done as described here... https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage. Hope this helps!

``CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, workstudy.cr_employment: execution of BeforeInsert caused by: System.QueryException: List has no rows for assignment to SObject Class.workstudy.cr_mgr_employment.createEmploymentName: line 20, column 1 Trigger.workstudy.cr_employment```

**Comment by ktallman** [comment]
Thanks for getting back to me Andrew. Unfortunately, I’m not a developer, so fixing the code or the test classes are both beyond my abilities. 

Ken

> On Apr 6, 2020, at 3:34 PM, Andrew Fawcett <notifications@github.com> wrote:
> 

﻿
Hi @ktallman the root error is not this tool it is that the test data the tool generats cannot predict the required fields for your child object. Because of this one of the other triggers on this object is failing, i have extracted the part of the error below. You have two options, fix the trigger so it tolerates null values in the object or enhance the test code this tool generates. This can be done as described here... https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage. Hope this helps!

``CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, workstudy.cr_employment: execution of BeforeInsert caused by: System.QueryException: List has no rows for assignment to SObject Class.workstudy.cr_mgr_employment.createEmploymentName: line 20, column 1 Trigger.workstudy.cr_employment```
